import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AosProvider from "@/providers/aos-provider";
import { MiiCharacterProvider } from "@/providers/character-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <AosProvider>
        <MiiCharacterProvider>
          <body className={inter.className}>
            {children}
          </body>
        </MiiCharacterProvider>
      </AosProvider>
    </html>
  );
}
