export const ITEMS_MALE = {
    head: [
        { id: 1, itemType: "head", src: "/items/head/head1.svg", position: { left: 50, top: 80 } },
        { id: 2, itemType: "head", src: "/items/head/head2.svg", position: { left: 50, top: 80 } },
        { id: 3, itemType: "head", src: "/items/head/head3.svg", position: { left: 50, top: 80 } },
        { id: 4, itemType: "head", src: "/items/head/head4.svg", position: { left: 37, top: 80 } },
        { id: 5, itemType: "head", src: "/items/head/head5.svg", position: { left: 28, top: 80 } },
    ],
    makeup: [
        { id: 1, itemType: "makeup", src: "/items/placeholder/empty.svg", position: { left: 56, top: 171 } },
        { id: 2, itemType: "makeup", src: "/items/makeup/makeup1.svg", position: { left: 56, top: 171 } },
        { id: 3, itemType: "makeup", src: "/items/makeup/makeup2.svg", position: { left: 56, top: 171 } },
        { id: 4, itemType: "makeup", src: "/items/makeup/makeup3.svg", position: { left: 49, top: 128 } },
        { id: 5, itemType: "makeup", src: "/items/makeup/makeup4.svg", position: { left: 54, top: 128 } },
        { id: 6, itemType: "makeup", src: "/items/makeup/makeup5.svg", position: { left: 72, top: 180 } },
    ],
    wrinkles: [
        { id: 1, itemType: "wrinkles", src: "/items/placeholder/empty.svg", position: { left: 57, top: 165 } },
        { id: 2, itemType: "wrinkles", src: "/items/wrinkles/wrinkles1.svg", position: { left: 57, top: 162 } },
        { id: 3, itemType: "wrinkles", src: "/items/wrinkles/wrinkles2.svg", position: { left: 82, top: 162 } },
        { id: 4, itemType: "wrinkles", src: "/items/wrinkles/wrinkles3.svg", position: { left: 65, top: 186 } },
        { id: 5, itemType: "wrinkles", src: "/items/wrinkles/wrinkles4.svg", position: { left: 53, top: 152 } },
        { id: 6, itemType: "wrinkles", src: "/items/wrinkles/wrinkles5.svg", position: { left: 58, top: 170 } },
        { id: 7, itemType: "wrinkles", src: "/items/wrinkles/wrinkles6.svg", position: { left: 103, top: 225 } },
    ],
    hair: [
        { id: 1, itemType: "hair", src: "/items/hair/mhair1.svg", placeholder: "/items/placeholder/hair/mphair1.svg", position: { left: 42, top: 65 } },
        { id: 2, itemType: "hair", src: "/items/hair/mhair2.svg", placeholder: "/items/placeholder/hair/mphair2.svg", position: { left: 36, top: 57 } },
        { id: 3, itemType: "hair", src: "/items/hair/mhair3.svg", placeholder: "/items/placeholder/hair/mphair3.svg", position: { left: 42, top: 65 } },
        { id: 4, itemType: "hair", src: "/items/hair/mhair4.svg", placeholder: "/items/placeholder/hair/mphair4.svg", position: { left: 42, top: 65 } },
        { id: 5, itemType: "hair", src: "/items/hair/mhair5.svg", placeholder: "/items/placeholder/hair/mphair5.svg", position: { left: 42, top: 65 } },
        { id: 6, itemType: "hair", src: "/items/hair/mhair6.svg", placeholder: "/items/placeholder/hair/mphair6.svg", position: { left: 43, top: 52 } },
        { id: 7, itemType: "hair", src: "/items/hair/mhair7.svg", placeholder: "/items/placeholder/hair/mphair7.svg", position: { left: 42, top: 52 } },
        { id: 8, itemType: "hair", src: "/items/hair/mhair8.svg", placeholder: "/items/placeholder/hair/mphair8.svg", position: { left: 42, top: 65 } },
        { id: 9, itemType: "hair", src: "/items/hair/mhair9.svg", placeholder: "/items/placeholder/hair/mphair9.svg", position: { left: 42, top: 66 } },
        { id: 10, itemType: "hair", src: "/items/hair/mhair10.svg", placeholder: "/items/placeholder/hair/mphair10.svg", position: { left: 42, top: 65 } },
        { id: 11, itemType: "hair", src: "/items/hair/mhair11.svg", placeholder: "/items/placeholder/hair/mphair11.svg", position: { left: 24, top: 47 } },
        { id: 12, itemType: "hair", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/empty.svg", position: { left: 42, top: 65 } },
    ],
    eyebrows: [
        { id: 1, itemType: "eyebrows", src: "/items/eyebrows/eyebrows1.svg", placeholder: "/items/placeholder/eyebrows/peyebrows1.svg", position: { left: 67, top: 130 } },
        { id: 2, itemType: "eyebrows", src: "/items/eyebrows/eyebrows2.svg", placeholder: "/items/placeholder/eyebrows/peyebrows2.svg", position: { left: 67, top: 133 } },
        { id: 3, itemType: "eyebrows", src: "/items/eyebrows/eyebrows3.svg", placeholder: "/items/placeholder/eyebrows/peyebrows3.svg", position: { left: 66, top: 130 } },
        { id: 4, itemType: "eyebrows", src: "/items/eyebrows/eyebrows4.svg", placeholder: "/items/placeholder/eyebrows/peyebrows4.svg", position: { left: 69, top: 132 } },
        { id: 5, itemType: "eyebrows", src: "/items/eyebrows/eyebrows5.svg", placeholder: "/items/placeholder/eyebrows/peyebrows5.svg", position: { left: 72, top: 131 } },
        { id: 6, itemType: "eyebrows", src: "/items/eyebrows/eyebrows6.svg", placeholder: "/items/placeholder/eyebrows/peyebrows6.svg", position: { left: 68, top: 135 } },
        { id: 7, itemType: "eyebrows", src: "/items/eyebrows/eyebrows7.svg", placeholder: "/items/placeholder/eyebrows/peyebrows7.svg", position: { left: 71, top: 133 } },
        { id: 8, itemType: "eyebrows", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/empty.svg", position: { left: 0, top: 0 } },
        { id: 9, itemType: "eyebrows", src: "/items/eyebrows/eyebrows9.svg", placeholder: "/items/placeholder/eyebrows/peyebrows9.svg", position: { left: 68, top: 133 } },
    ],
    eyes: [
        { id: 1, itemType: "eyes", src: "/items/eyes/eyes1.svg", placeholder: "/items/placeholder/eyes/peyes1.svg", position: { left: 67, top: 148 } },
        { id: 2, itemType: "eyes", src: "/items/eyes/eyes2.svg", placeholder: "/items/placeholder/eyes/peyes2.svg", position: { left: 61, top: 147 } },
        { id: 3, itemType: "eyes", src: "/items/eyes/eyes3.svg", placeholder: "/items/placeholder/eyes/peyes3.svg", position: { left: 63, top: 144 } },
        { id: 4, itemType: "eyes", src: "/items/eyes/eyes4.svg", placeholder: "/items/placeholder/eyes/peyes4.svg", position: { left: 71, top: 143 } },
        { id: 5, itemType: "eyes", src: "/items/eyes/eyes5.svg", placeholder: "/items/placeholder/eyes/peyes5.svg", position: { left: 71, top: 146 } },
        { id: 6, itemType: "eyes", src: "/items/eyes/eyes6.svg", placeholder: "/items/placeholder/eyes/peyes6.svg", position: { left: 69, top: 150 } },
        { id: 7, itemType: "eyes", src: "/items/eyes/eyes7.svg", placeholder: "/items/placeholder/eyes/peyes7.svg", position: { left: 74, top: 145 } },
        { id: 8, itemType: "eyes", src: "/items/eyes/eyes8.svg", placeholder: "/items/placeholder/eyes/peyes8.svg", position: { left: 72, top: 146 } },
        { id: 9, itemType: "eyes", src: "/items/eyes/eyes9.svg", placeholder: "/items/placeholder/eyes/peyes9.svg", position: { left: 72, top: 143 } },
        { id: 10, itemType: "eyes", src: "/items/eyes/eyes10.svg", placeholder: "/items/placeholder/eyes/peyes10.svg", position: { left: 73, top: 148 } },
        { id: 11, itemType: "eyes", src: "/items/eyes/eyes11.svg", placeholder: "/items/placeholder/eyes/peyes11.svg", position: { left: 70, top: 148 } },
        { id: 12, itemType: "eyes", src: "/items/eyes/eyes12.svg", placeholder: "/items/placeholder/eyes/peyes12.svg", position: { left: 73, top: 148 } },
        { id: 13, itemType: "eyes", src: "/items/eyes/eyes13.svg", placeholder: "/items/placeholder/eyes/peyes13.svg", position: { left: 74, top: 155 } },
        { id: 14, itemType: "eyes", src: "/items/eyes/eyes14.svg", placeholder: "/items/placeholder/eyes/peyes14.png", position: { left: 62, top: 150 } },
        { id: 15, itemType: "eyes", src: "/items/eyes/eyes15.svg", placeholder: "/items/placeholder/eyes/peyes15.png", position: { left: 62, top: 150 } },
        { id: 16, itemType: "eyes", src: "/items/eyes/eyes16.svg", placeholder: "/items/placeholder/eyes/peyes16.svg", position: { left: 69, top: 148 } },
        { id: 17, itemType: "eyes", src: "/items/eyes/eyes17.svg", placeholder: "/items/placeholder/eyes/peyes17.svg", position: { left: 65, top: 147 } },
        { id: 18, itemType: "eyes", src: "/items/eyes/eyes18.svg", placeholder: "/items/placeholder/eyes/peyes18.svg", position: { left: 68, top: 146 } },
        { id: 19, itemType: "eyes", src: "/items/eyes/eyes19.svg", placeholder: "/items/placeholder/eyes/peyes19.svg", position: { left: 66, top: 147 } },
        { id: 20, itemType: "eyes", src: "/items/eyes/eyes20.svg", placeholder: "/items/placeholder/eyes/peyes20.svg", position: { left: 66, top: 132 } },
        { id: 21, itemType: "eyes", src: "/items/eyes/eyes21.svg", placeholder: "/items/placeholder/eyes/peyes21.svg", position: { left: 58, top: 122 } },
        { id: 22, itemType: "eyes", src: "/items/eyes/eyes22.svg", placeholder: "/items/placeholder/eyes/peyes22.svg", position: { left: 75, top: 148 } },
        { id: 23, itemType: "eyes", src: "/items/eyes/eyes23.svg", placeholder: "/items/placeholder/eyes/peyes23.svg", position: { left: 59, top: 143 } },
        { id: 24, itemType: "eyes", src: "/items/eyes/eyes24.svg", placeholder: "/items/placeholder/eyes/peyes24.svg", position: { left: 72, top: 144 } },
    ],
    nose: [
        { id: 1, itemType: "nose", src: "/items/nose/nose1.svg", placeholder: "/items/placeholder/nose/pnose1.svg", position: { left: 106, top: 165 } },
        { id: 2, itemType: "nose", src: "/items/nose/nose2.svg", placeholder: "/items/placeholder/nose/pnose2.svg", position: { left: 103, top: 184 } },
        { id: 3, itemType: "nose", src: "/items/nose/nose3.svg", placeholder: "/items/placeholder/nose/pnose3.svg", position: { left: 106, top: 182 } },
        { id: 4, itemType: "nose", src: "/items/nose/nose4.svg", placeholder: "/items/placeholder/nose/pnose4.svg", position: { left: 102, top: 182 } },
        { id: 5, itemType: "nose", src: "/items/nose/nose5.svg", placeholder: "/items/placeholder/nose/pnose5.svg", position: { left: 108, top: 181 } },
        { id: 6, itemType: "nose", src: "/items/nose/nose6.svg", placeholder: "/items/placeholder/nose/pnose6.svg", position: { left: 101, top: 179 } },
        { id: 7, itemType: "nose", src: "/items/nose/nose7.svg", placeholder: "/items/placeholder/nose/pnose7.svg", position: { left: 102, top: 178 } },
        { id: 8, itemType: "nose", src: "/items/nose/nose8.svg", placeholder: "/items/placeholder/nose/pnose8.svg", position: { left: 106, top: 174 } },
        { id: 9, itemType: "nose", src: "/items/nose/nose9.svg", placeholder: "/items/placeholder/nose/pnose9.svg", position: { left: 101, top: 169 } },
        { id: 10, itemType: "nose", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/empty.svg", position: { left: 0, top: 0 } },
        { id: 11, itemType: "nose", src: "/items/nose/nose11.svg", placeholder: "/items/placeholder/nose/pnose11.svg", position: { left: 103, top: 173 } },
        { id: 12, itemType: "nose", src: "/items/nose/nose12.svg", placeholder: "/items/placeholder/nose/pnose12.svg", position: { left: 109, top: 167 } },
    ],
    mouth: [
        { id: 1, itemType: "mouth", src: "/items/mouth/mouth1.svg", placeholder: "/items/placeholder/mouth/pmouth1.svg", position: { left: 103, top: 213 } },
        { id: 2, itemType: "mouth", src: "/items/mouth/mouth2.svg", placeholder: "/items/placeholder/mouth/pmouth2.svg", position: { left: 97, top: 211 } },
        { id: 3, itemType: "mouth", src: "/items/mouth/mouth3.svg", placeholder: "/items/placeholder/mouth/pmouth3.svg", position: { left: 97, top: 210 } },
        { id: 4, itemType: "mouth", src: "/items/mouth/mouth4.svg", placeholder: "/items/placeholder/mouth/pmouth4.svg", position: { left: 96, top: 211 } },
        { id: 5, itemType: "mouth", src: "/items/mouth/mouth5.svg", placeholder: "/items/placeholder/mouth/pmouth5.svg", position: { left: 96, top: 210 } },
        { id: 6, itemType: "mouth", src: "/items/mouth/mouth6.svg", placeholder: "/items/placeholder/mouth/pmouth6.svg", position: { left: 95, top: 213 } },
        { id: 7, itemType: "mouth", src: "/items/mouth/mouth7.svg", placeholder: "/items/placeholder/mouth/pmouth7.svg", position: { left: 95, top: 208 } },
        { id: 8, itemType: "mouth", src: "/items/mouth/mouth8.svg", placeholder: "/items/placeholder/mouth/pmouth8.svg", position: { left: 101, top: 208 } },
        { id: 9, itemType: "mouth", src: "/items/mouth/mouth9.svg", placeholder: "/items/placeholder/mouth/pmouth9.svg", position: { left: 107, top: 207 } },
        { id: 10, itemType: "mouth", src: "/items/mouth/mouth10.svg", placeholder: "/items/placeholder/mouth/pmouth10.svg", position: { left: 95, top: 206 } },
        { id: 11, itemType: "mouth", src: "/items/mouth/mouth11.svg", placeholder: "/items/placeholder/mouth/pmouth11.svg", position: { left: 98, top: 212 } },
        { id: 12, itemType: "mouth", src: "/items/mouth/mouth12.svg", placeholder: "/items/placeholder/mouth/pmouth12.svg", position: { left: 98, top: 212 } },
        { id: 13, itemType: "mouth", src: "/items/mouth/mouth13.svg", placeholder: "/items/placeholder/mouth/pmouth13.svg", position: { left: 101, top: 208 } },
        { id: 14, itemType: "mouth", src: "/items/mouth/mouth14.svg", placeholder: "/items/placeholder/mouth/pmouth14.svg", position: { left: 103, top: 207 } },
        { id: 15, itemType: "mouth", src: "/items/mouth/mouth15.svg", placeholder: "/items/placeholder/mouth/pmouth15.svg", position: { left: 93, top: 205 } },
        { id: 16, itemType: "mouth", src: "/items/mouth/mouth16.svg", placeholder: "/items/placeholder/mouth/pmouth16.svg", position: { left: 107, top: 212 } },
        { id: 17, itemType: "mouth", src: "/items/mouth/mouth17.svg", placeholder: "/items/placeholder/mouth/pmouth17.svg", position: { left: 101, top: 208 } },
        { id: 18, itemType: "mouth", src: "/items/mouth/mouth18.svg", placeholder: "/items/placeholder/mouth/pmouth18.svg", position: { left: 102, top: 210 } },
        { id: 19, itemType: "mouth", src: "/items/mouth/mouth19.svg", placeholder: "/items/placeholder/mouth/pmouth19.svg", position: { left: 112, top: 206 } },
        { id: 20, itemType: "mouth", src: "/items/mouth/mouth20.svg", placeholder: "/items/placeholder/mouth/pmouth20.svg", position: { left: 96, top: 209 } },
        { id: 21, itemType: "mouth", src: "/items/mouth/mouth21.svg", placeholder: "/items/placeholder/mouth/pmouth21.svg", position: { left: 98, top: 207 } },
        { id: 22, itemType: "mouth", src: "/items/mouth/mouth22.svg", placeholder: "/items/placeholder/mouth/pmouth22.svg", position: { left: 82, top: 208 } },
        { id: 23, itemType: "mouth", src: "/items/mouth/mouth23.svg", placeholder: "/items/placeholder/mouth/pmouth23.png", position: { left: 88, top: 209 } },
        { id: 24, itemType: "mouth", src: "/items/mouth/mouth24.svg", placeholder: "/items/placeholder/mouth/pmouth24.png", position: { left: 76, top: 205 } },
    ],
    glasses: [
        { id: 1, itemType: "glasses", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/glasses/empty-head.svg", position: { left: 65, top: 143 } },
        { id: 2, itemType: "glasses", src: "/items/glasses/glasses1.svg", placeholder: "/items/placeholder/glasses/pglasses1.svg", position: { left: 64, top: 143 } },
        { id: 3, itemType: "glasses", src: "/items/glasses/glasses2.svg", placeholder: "/items/placeholder/glasses/pglasses2.svg", position: { left: 63, top: 145 } },
        { id: 4, itemType: "glasses", src: "/items/glasses/glasses3.svg", placeholder: "/items/placeholder/glasses/pglasses3.svg", position: { left: 65, top: 138 } },
        { id: 5, itemType: "glasses", src: "/items/glasses/glasses4.svg", placeholder: "/items/placeholder/glasses/pglasses4.svg", position: { left: 58, top: 140 } },
        { id: 6, itemType: "glasses", src: "/items/glasses/glasses5.svg", placeholder: "/items/placeholder/glasses/pglasses5.svg", position: { left: 63, top: 143 } },
        { id: 7, itemType: "glasses", src: "/items/glasses/glasses6.svg", placeholder: "/items/placeholder/glasses/pglasses6.svg", position: { left: 62, top: 142 } },
        { id: 8, itemType: "glasses", src: "/items/glasses/glasses7.svg", placeholder: "/items/placeholder/glasses/pglasses7.svg", position: { left: 65, top: 141 } },
    ],
    outfit: [
        { id: 1, itemType: "outfit", src: "/items/outfit/moutfit1.svg", position: { left: 15, top: 230 } },
        { id: 2, itemType: "outfit", src: "/items/outfit/moutfit2.svg", position: { left: 15, top: 230 } },
        { id: 3, itemType: "outfit", src: "/items/outfit/moutfit3.svg", position: { left: 15, top: 230 } },
    ],
    hat: [
        { id: 1, itemType: "hat", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/empty.svg", position: { left: 0, top: 0 } },
        { id: 2, itemType: "hat", src: "/items/hat/hat1.svg", placeholder: "/items/hat/hat1.svg", position: { left: 46, top: 64 } },
        { id: 3, itemType: "hat", src: "/items/hat/hat2.svg", placeholder: "/items/hat/hat2.svg", position: { left: 44, top: 115 } },
        { id: 4, itemType: "hat", src: "/items/hat/hat3.svg", placeholder: "/items/hat/hat3.svg", position: { left: 18, top: 50 } },
        { id: 5, itemType: "hat", src: "/items/hat/hat4.svg", placeholder: "/items/hat/hat4.svg", position: { left: 48, top: 50 } },
        { id: 6, itemType: "hat", src: "/items/hat/hat5.svg", placeholder: "/items/hat/hat5.svg", position: { left: 31, top: 40 } },
        { id: 7, itemType: "hat", src: "/items/hat/hat6.svg", placeholder: "/items/hat/hat6.svg", position: { left: 40, top: 52 } },
        { id: 8, itemType: "hat", src: "/items/hat/hat7.svg", placeholder: "/items/hat/hat7.svg", position: { left: 45, top: 0 } },
        { id: 9, itemType: "hat", src: "/items/hat/hat8.svg", placeholder: "/items/hat/hat8.svg", position: { left: 42, top: 100 } },
        { id: 10, itemType: "hat", src: "/items/hat/hat9.svg", placeholder: "/items/hat/hat9.svg", position: { left: 28, top: 28 } },
        { id: 11, itemType: "hat", src: "/items/hat/hat10.svg", placeholder: "/items/hat/hat10.svg", position: { left: 35, top: 12 } },
        { id: 12, itemType: "hat", src: "/items/hat/hat11.svg", placeholder: "/items/hat/hat11.svg", position: { left: 47, top: 16 } },
        { id: 13, itemType: "hat", src: "/items/hat/hat12.svg", placeholder: "/items/hat/hat12.svg", position: { left: 45, top: 20 } },
        { id: 14, itemType: "hat", src: "/items/hat/hat13.svg", placeholder: "/items/hat/hat13.svg", position: { left: 20, top: 35 } },
        { id: 15, itemType: "hat", src: "/items/hat/hat14.svg", placeholder: "/items/hat/hat14.svg", position: { left: 120, top: 70 } },
        { id: 16, itemType: "hat", src: "/items/hat/hat15.svg", placeholder: "/items/hat/hat15.svg", position: { left: 35, top: 20 } },
        { id: 17, itemType: "hat", src: "/items/hat/hat16.svg", placeholder: "/items/hat/hat16.svg", position: { left: 49, top: 40 } },
        { id: 18, itemType: "hat", src: "/items/hat/hat17.svg", placeholder: "/items/hat/hat17.svg", position: { left: 22, top: 12 } },
    ],
    accessory: [
        { id: 1, itemType: "accessory", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/empty.svg", position: { left: 0, top: 0 } },
        { id: 2, itemType: "accessory", src: "/items/accessory/accessory1.svg", placeholder: "/items/accessory/accessory1.svg", position: { left: 105, top: 242 } },
        { id: 3, itemType: "accessory", src: "/items/accessory/accessory2.svg", placeholder: "/items/accessory/accessory2.svg", position: { left: 98, top: 243 } },
        { id: 4, itemType: "accessory", src: "/items/accessory/accessory3.svg", placeholder: "/items/accessory/accessory3.svg", position: { left: 92, top: 238 } },
        { id: 5, itemType: "accessory", src: "/items/accessory/accessory4.svg", placeholder: "/items/accessory/accessory4.svg", position: { left: 31, top: 234 } },
        { id: 6, itemType: "accessory", src: "/items/accessory/accessory5.svg", placeholder: "/items/accessory/accessory5.svg", position: { left: 120, top: 260 } },
        { id: 7, itemType: "accessory", src: "/items/accessory/accessory6.svg", placeholder: "/items/accessory/accessory6.svg", position: { left: 45, top: 170 } },
        { id: 8, itemType: "accessory", src: "/items/accessory/accessory7.svg", placeholder: "/items/accessory/accessory7.svg", position: { left: 16, top: 184 } },
        { id: 9, itemType: "accessory", src: "/items/accessory/accessory8.svg", placeholder: "/items/accessory/accessory8.svg", position: { left: 42, top: 160 } },
        //{ id: 10, itemType: "accessory", src: "/items/accessory/accessory9.svg", placeholder: "/items/accessory/accessory9.svg", position: { left: 0, top: 0 } },
    ],
    beard: [
        { id: 1, itemType: "beard", src: "/items/beard/beard1.svg", position: { left: 0, top: 0 } },
        { id: 2, itemType: "beard", src: "/items/beard/beard2.svg", position: { left: 0, top: 0 } },
        { id: 3, itemType: "beard", src: "/items/beard/beard3.svg", position: { left: 0, top: 0 } },
        { id: 4, itemType: "beard", src: "/items/beard/beard4.svg", position: { left: 0, top: 0 } },
    ],
};

export const ITEMS_FEMALE = {
    head: [
        { id: 1, itemType: "head", src: "/items/head/head1.svg", position: { left: 50, top: 80 } },
        { id: 2, itemType: "head", src: "/items/head/head2.svg", position: { left: 50, top: 80 } },
        { id: 3, itemType: "head", src: "/items/head/head3.svg", position: { left: 50, top: 80 } },
        { id: 4, itemType: "head", src: "/items/head/head4.svg", position: { left: 37, top: 80 } },
        { id: 5, itemType: "head", src: "/items/head/head5.svg", position: { left: 28, top: 80 } },
    ],
    makeup: [
        { id: 1, itemType: "makeup", src: "/items/placeholder/empty.svg", position: { left: 56, top: 171 } },
        { id: 2, itemType: "makeup", src: "/items/makeup/makeup1.svg", position: { left: 56, top: 171 } },
        { id: 3, itemType: "makeup", src: "/items/makeup/makeup2.svg", position: { left: 56, top: 171 } },
        { id: 4, itemType: "makeup", src: "/items/makeup/makeup3.svg", position: { left: 49, top: 128 } },
        { id: 5, itemType: "makeup", src: "/items/makeup/makeup4.svg", position: { left: 54, top: 128 } },
        { id: 6, itemType: "makeup", src: "/items/makeup/makeup5.svg", position: { left: 72, top: 180 } },
    ],
    wrinkles: [
        { id: 1, itemType: "wrinkles", src: "/items/placeholder/empty.svg", position: { left: 57, top: 165 } },
        { id: 2, itemType: "wrinkles", src: "/items/wrinkles/wrinkles1.svg", position: { left: 57, top: 162 } },
        { id: 3, itemType: "wrinkles", src: "/items/wrinkles/wrinkles2.svg", position: { left: 82, top: 162 } },
        { id: 4, itemType: "wrinkles", src: "/items/wrinkles/wrinkles3.svg", position: { left: 65, top: 186 } },
        { id: 5, itemType: "wrinkles", src: "/items/wrinkles/wrinkles4.svg", position: { left: 53, top: 152 } },
        { id: 6, itemType: "wrinkles", src: "/items/wrinkles/wrinkles5.svg", position: { left: 58, top: 170 } },
        { id: 7, itemType: "wrinkles", src: "/items/wrinkles/wrinkles6.svg", position: { left: 103, top: 225 } },
    ],
    hair: [
        { id: 1, itemType: "hair", src: "/items/hair/fhair1.svg", placeholder: "/items/placeholder/hair/fphair1.svg", position: { left: 35, top: 56 } },
        { id: 2, itemType: "hair", src: "/items/hair/fhair2.svg", placeholder: "/items/placeholder/hair/fphair2.svg", position: { left: 10, top: 30 } },
        { id: 3, itemType: "hair", src: "/items/hair/fhair3.svg", placeholder: "/items/placeholder/hair/fphair3.svg", position: { left: 10, top: 56 } },
        { id: 4, itemType: "hair", src: "/items/hair/fhair4.svg", placeholder: "/items/placeholder/hair/fphair4.svg", position: { left: 35, top: 61 } },
        { id: 5, itemType: "hair", src: "/items/hair/fhair5.svg", placeholder: "/items/placeholder/hair/fphair5.svg", position: { left: 26, top: 64 } },
        { id: 6, itemType: "hair", src: "/items/hair/fhair6.svg", placeholder: "/items/placeholder/hair/fphair6.svg", position: { left: 0, top: 61 } },
        { id: 7, itemType: "hair", src: "/items/hair/fhair7.svg", placeholder: "/items/placeholder/hair/fphair7.svg", position: { left: 35, top: 56 } },
        { id: 8, itemType: "hair", src: "/items/hair/fhair8.svg", placeholder: "/items/placeholder/hair/fphair8.svg", position: { left: 1, top: 62 } },
        { id: 9, itemType: "hair", src: "/items/hair/fhair9.svg", placeholder: "/items/placeholder/hair/fphair9.svg", position: { left: 3, top: 57 } },
        { id: 10, itemType: "hair", src: "/items/hair/fhair10.svg", placeholder: "/items/placeholder/hair/fphair10.svg", position: { left: 35, top: 56 } },
        { id: 11, itemType: "hair", src: "/items/hair/fhair11.svg", placeholder: "/items/placeholder/hair/fphair11.svg", position: { left: 29, top: 58 } },
        { id: 12, itemType: "hair", src: "/items/hair/fhair12.svg", placeholder: "/items/placeholder/hair/fphair12.svg", position: { left: 43, top: 53 } },
        { id: 13, itemType: "hair", src: "/items/hair/fhair13.svg", placeholder: "/items/placeholder/hair/fphair13.svg", position: { left: 35, top: 60 } },
        { id: 14, itemType: "hair", src: "/items/hair/fhair14.svg", placeholder: "/items/placeholder/hair/fphair14.svg", position: { left: 51, top: 70 } },
        { id: 15, itemType: "hair", src: "/items/hair/fhair15.svg", placeholder: "/items/placeholder/hair/fphair15.svg", position: { left: 40, top: 62 } },
        { id: 16, itemType: "hair", src: "/items/hair/fhair16.svg", placeholder: "/items/placeholder/hair/fphair16.svg", position: { left: 17, top: 46 } },
        { id: 17, itemType: "hair", src: "/items/hair/fhair17.svg", placeholder: "/items/placeholder/hair/fphair17.svg", position: { left: -4, top: 65 } },
        { id: 18, itemType: "hair", src: "/items/hair/fhair18.svg", placeholder: "/items/placeholder/hair/fphair18.svg", position: { left: 35, top: 70 } },
        { id: 19, itemType: "hair", src: "/items/hair/fhair19.svg", placeholder: "/items/placeholder/hair/fphair19.svg", position: { left: -5, top: 72 } },
        { id: 20, itemType: "hair", src: "/items/hair/fhair20.svg", placeholder: "/items/placeholder/hair/fphair20.svg", position: { left: 0, top: 56 } },
        { id: 21, itemType: "hair", src: "/items/hair/fhair21.svg", placeholder: "/items/placeholder/hair/fphair21.svg", position: { left: 11, top: 54 } },
    ],
    eyebrows: [
        { id: 1, itemType: "eyebrows", src: "/items/eyebrows/eyebrows1.svg", placeholder: "/items/placeholder/eyebrows/peyebrows1.svg", position: { left: 67, top: 130 } },
        { id: 2, itemType: "eyebrows", src: "/items/eyebrows/eyebrows2.svg", placeholder: "/items/placeholder/eyebrows/peyebrows2.svg", position: { left: 67, top: 133 } },
        { id: 3, itemType: "eyebrows", src: "/items/eyebrows/eyebrows3.svg", placeholder: "/items/placeholder/eyebrows/peyebrows3.svg", position: { left: 66, top: 130 } },
        { id: 4, itemType: "eyebrows", src: "/items/eyebrows/eyebrows4.svg", placeholder: "/items/placeholder/eyebrows/peyebrows4.svg", position: { left: 69, top: 132 } },
        { id: 5, itemType: "eyebrows", src: "/items/eyebrows/eyebrows5.svg", placeholder: "/items/placeholder/eyebrows/peyebrows5.svg", position: { left: 72, top: 131 } },
        { id: 6, itemType: "eyebrows", src: "/items/eyebrows/eyebrows6.svg", placeholder: "/items/placeholder/eyebrows/peyebrows6.svg", position: { left: 68, top: 135 } },
        { id: 7, itemType: "eyebrows", src: "/items/eyebrows/eyebrows7.svg", placeholder: "/items/placeholder/eyebrows/peyebrows7.svg", position: { left: 71, top: 133 } },
        { id: 8, itemType: "eyebrows", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/empty.svg", position: { left: 0, top: 0 } },
        { id: 9, itemType: "eyebrows", src: "/items/eyebrows/eyebrows9.svg", placeholder: "/items/placeholder/eyebrows/peyebrows9.svg", position: { left: 68, top: 133 } },
    ],
    eyes: [
        { id: 1, itemType: "eyes", src: "/items/eyes/eyes1.svg", placeholder: "/items/placeholder/eyes/peyes1.svg", position: { left: 67, top: 148 } },
        { id: 2, itemType: "eyes", src: "/items/eyes/eyes2.svg", placeholder: "/items/placeholder/eyes/peyes2.svg", position: { left: 61, top: 147 } },
        { id: 3, itemType: "eyes", src: "/items/eyes/eyes3.svg", placeholder: "/items/placeholder/eyes/peyes3.svg", position: { left: 63, top: 144 } },
        { id: 4, itemType: "eyes", src: "/items/eyes/eyes4.svg", placeholder: "/items/placeholder/eyes/peyes4.svg", position: { left: 71, top: 143 } },
        { id: 5, itemType: "eyes", src: "/items/eyes/eyes5.svg", placeholder: "/items/placeholder/eyes/peyes5.svg", position: { left: 71, top: 146 } },
        { id: 6, itemType: "eyes", src: "/items/eyes/eyes6.svg", placeholder: "/items/placeholder/eyes/peyes6.svg", position: { left: 69, top: 150 } },
        { id: 7, itemType: "eyes", src: "/items/eyes/eyes7.svg", placeholder: "/items/placeholder/eyes/peyes7.svg", position: { left: 74, top: 145 } },
        { id: 8, itemType: "eyes", src: "/items/eyes/eyes8.svg", placeholder: "/items/placeholder/eyes/peyes8.svg", position: { left: 72, top: 146 } },
        { id: 9, itemType: "eyes", src: "/items/eyes/eyes9.svg", placeholder: "/items/placeholder/eyes/peyes9.svg", position: { left: 72, top: 143 } },
        { id: 10, itemType: "eyes", src: "/items/eyes/eyes10.svg", placeholder: "/items/placeholder/eyes/peyes10.svg", position: { left: 73, top: 148 } },
        { id: 11, itemType: "eyes", src: "/items/eyes/eyes11.svg", placeholder: "/items/placeholder/eyes/peyes11.svg", position: { left: 70, top: 148 } },
        { id: 12, itemType: "eyes", src: "/items/eyes/eyes12.svg", placeholder: "/items/placeholder/eyes/peyes12.svg", position: { left: 73, top: 148 } },
        { id: 13, itemType: "eyes", src: "/items/eyes/eyes13.svg", placeholder: "/items/placeholder/eyes/peyes13.svg", position: { left: 74, top: 155 } },
        { id: 14, itemType: "eyes", src: "/items/eyes/eyes14.svg", placeholder: "/items/placeholder/eyes/peyes14.png", position: { left: 62, top: 150 } },
        { id: 15, itemType: "eyes", src: "/items/eyes/eyes15.svg", placeholder: "/items/placeholder/eyes/peyes15.png", position: { left: 62, top: 150 } },
        { id: 16, itemType: "eyes", src: "/items/eyes/eyes16.svg", placeholder: "/items/placeholder/eyes/peyes16.svg", position: { left: 69, top: 148 } },
        { id: 17, itemType: "eyes", src: "/items/eyes/eyes17.svg", placeholder: "/items/placeholder/eyes/peyes17.svg", position: { left: 65, top: 147 } },
        { id: 18, itemType: "eyes", src: "/items/eyes/eyes18.svg", placeholder: "/items/placeholder/eyes/peyes18.svg", position: { left: 68, top: 146 } },
        { id: 19, itemType: "eyes", src: "/items/eyes/eyes19.svg", placeholder: "/items/placeholder/eyes/peyes19.svg", position: { left: 66, top: 147 } },
        { id: 20, itemType: "eyes", src: "/items/eyes/eyes20.svg", placeholder: "/items/placeholder/eyes/peyes20.svg", position: { left: 66, top: 132 } },
        { id: 21, itemType: "eyes", src: "/items/eyes/eyes21.svg", placeholder: "/items/placeholder/eyes/peyes21.svg", position: { left: 58, top: 122 } },
        { id: 22, itemType: "eyes", src: "/items/eyes/eyes22.svg", placeholder: "/items/placeholder/eyes/peyes22.svg", position: { left: 75, top: 148 } },
        { id: 23, itemType: "eyes", src: "/items/eyes/eyes23.svg", placeholder: "/items/placeholder/eyes/peyes23.svg", position: { left: 59, top: 143 } },
        { id: 24, itemType: "eyes", src: "/items/eyes/eyes24.svg", placeholder: "/items/placeholder/eyes/peyes24.svg", position: { left: 72, top: 144 } },
    ],
    nose: [
        { id: 1, itemType: "nose", src: "/items/nose/nose1.svg", placeholder: "/items/placeholder/nose/pnose1.svg", position: { left: 106, top: 165 } },
        { id: 2, itemType: "nose", src: "/items/nose/nose2.svg", placeholder: "/items/placeholder/nose/pnose2.svg", position: { left: 103, top: 184 } },
        { id: 3, itemType: "nose", src: "/items/nose/nose3.svg", placeholder: "/items/placeholder/nose/pnose3.svg", position: { left: 106, top: 182 } },
        { id: 4, itemType: "nose", src: "/items/nose/nose4.svg", placeholder: "/items/placeholder/nose/pnose4.svg", position: { left: 102, top: 182 } },
        { id: 5, itemType: "nose", src: "/items/nose/nose5.svg", placeholder: "/items/placeholder/nose/pnose5.svg", position: { left: 108, top: 181 } },
        { id: 6, itemType: "nose", src: "/items/nose/nose6.svg", placeholder: "/items/placeholder/nose/pnose6.svg", position: { left: 101, top: 179 } },
        { id: 7, itemType: "nose", src: "/items/nose/nose7.svg", placeholder: "/items/placeholder/nose/pnose7.svg", position: { left: 102, top: 178 } },
        { id: 8, itemType: "nose", src: "/items/nose/nose8.svg", placeholder: "/items/placeholder/nose/pnose8.svg", position: { left: 106, top: 174 } },
        { id: 9, itemType: "nose", src: "/items/nose/nose9.svg", placeholder: "/items/placeholder/nose/pnose9.svg", position: { left: 101, top: 169 } },
        { id: 10, itemType: "nose", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/empty.svg", position: { left: 0, top: 0 } },
        { id: 11, itemType: "nose", src: "/items/nose/nose11.svg", placeholder: "/items/placeholder/nose/pnose11.svg", position: { left: 103, top: 173 } },
        { id: 12, itemType: "nose", src: "/items/nose/nose12.svg", placeholder: "/items/placeholder/nose/pnose12.svg", position: { left: 109, top: 167 } },
    ],
    mouth: [
        { id: 1, itemType: "mouth", src: "/items/mouth/mouth1.svg", placeholder: "/items/placeholder/mouth/pmouth1.svg", position: { left: 103, top: 213 } },
        { id: 2, itemType: "mouth", src: "/items/mouth/mouth2.svg", placeholder: "/items/placeholder/mouth/pmouth2.svg", position: { left: 97, top: 211 } },
        { id: 3, itemType: "mouth", src: "/items/mouth/mouth3.svg", placeholder: "/items/placeholder/mouth/pmouth3.svg", position: { left: 97, top: 210 } },
        { id: 4, itemType: "mouth", src: "/items/mouth/mouth4.svg", placeholder: "/items/placeholder/mouth/pmouth4.svg", position: { left: 96, top: 211 } },
        { id: 5, itemType: "mouth", src: "/items/mouth/mouth5.svg", placeholder: "/items/placeholder/mouth/pmouth5.svg", position: { left: 96, top: 210 } },
        { id: 6, itemType: "mouth", src: "/items/mouth/mouth6.svg", placeholder: "/items/placeholder/mouth/pmouth6.svg", position: { left: 95, top: 213 } },
        { id: 7, itemType: "mouth", src: "/items/mouth/mouth7.svg", placeholder: "/items/placeholder/mouth/pmouth7.svg", position: { left: 95, top: 208 } },
        { id: 8, itemType: "mouth", src: "/items/mouth/mouth8.svg", placeholder: "/items/placeholder/mouth/pmouth8.svg", position: { left: 101, top: 208 } },
        { id: 9, itemType: "mouth", src: "/items/mouth/mouth9.svg", placeholder: "/items/placeholder/mouth/pmouth9.svg", position: { left: 107, top: 207 } },
        { id: 10, itemType: "mouth", src: "/items/mouth/mouth10.svg", placeholder: "/items/placeholder/mouth/pmouth10.svg", position: { left: 95, top: 206 } },
        { id: 11, itemType: "mouth", src: "/items/mouth/mouth11.svg", placeholder: "/items/placeholder/mouth/pmouth11.svg", position: { left: 98, top: 212 } },
        { id: 12, itemType: "mouth", src: "/items/mouth/mouth12.svg", placeholder: "/items/placeholder/mouth/pmouth12.svg", position: { left: 98, top: 212 } },
        { id: 13, itemType: "mouth", src: "/items/mouth/mouth13.svg", placeholder: "/items/placeholder/mouth/pmouth13.svg", position: { left: 101, top: 208 } },
        { id: 14, itemType: "mouth", src: "/items/mouth/mouth14.svg", placeholder: "/items/placeholder/mouth/pmouth14.svg", position: { left: 103, top: 207 } },
        { id: 15, itemType: "mouth", src: "/items/mouth/mouth15.svg", placeholder: "/items/placeholder/mouth/pmouth15.svg", position: { left: 93, top: 205 } },
        { id: 16, itemType: "mouth", src: "/items/mouth/mouth16.svg", placeholder: "/items/placeholder/mouth/pmouth16.svg", position: { left: 107, top: 212 } },
        { id: 17, itemType: "mouth", src: "/items/mouth/mouth17.svg", placeholder: "/items/placeholder/mouth/pmouth17.svg", position: { left: 101, top: 208 } },
        { id: 18, itemType: "mouth", src: "/items/mouth/mouth18.svg", placeholder: "/items/placeholder/mouth/pmouth18.svg", position: { left: 102, top: 210 } },
        { id: 19, itemType: "mouth", src: "/items/mouth/mouth19.svg", placeholder: "/items/placeholder/mouth/pmouth19.svg", position: { left: 112, top: 206 } },
        { id: 20, itemType: "mouth", src: "/items/mouth/mouth20.svg", placeholder: "/items/placeholder/mouth/pmouth20.svg", position: { left: 96, top: 209 } },
        { id: 21, itemType: "mouth", src: "/items/mouth/mouth21.svg", placeholder: "/items/placeholder/mouth/pmouth21.svg", position: { left: 98, top: 207 } },
        { id: 22, itemType: "mouth", src: "/items/mouth/mouth22.svg", placeholder: "/items/placeholder/mouth/pmouth22.svg", position: { left: 82, top: 208 } },
        { id: 23, itemType: "mouth", src: "/items/mouth/mouth23.svg", placeholder: "/items/placeholder/mouth/pmouth23.png", position: { left: 88, top: 209 } },
        { id: 24, itemType: "mouth", src: "/items/mouth/mouth24.svg", placeholder: "/items/placeholder/mouth/pmouth24.png", position: { left: 76, top: 205 } },
    ],
    glasses: [
        { id: 1, itemType: "glasses", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/glasses/empty-head.svg", position: { left: 65, top: 143 } },
        { id: 2, itemType: "glasses", src: "/items/glasses/glasses1.svg", placeholder: "/items/placeholder/glasses/pglasses1.svg", position: { left: 64, top: 143 } },
        { id: 3, itemType: "glasses", src: "/items/glasses/glasses2.svg", placeholder: "/items/placeholder/glasses/pglasses2.svg", position: { left: 63, top: 145 } },
        { id: 4, itemType: "glasses", src: "/items/glasses/glasses3.svg", placeholder: "/items/placeholder/glasses/pglasses3.svg", position: { left: 65, top: 138 } },
        { id: 5, itemType: "glasses", src: "/items/glasses/glasses4.svg", placeholder: "/items/placeholder/glasses/pglasses4.svg", position: { left: 58, top: 140 } },
        { id: 6, itemType: "glasses", src: "/items/glasses/glasses5.svg", placeholder: "/items/placeholder/glasses/pglasses5.svg", position: { left: 63, top: 143 } },
        { id: 7, itemType: "glasses", src: "/items/glasses/glasses6.svg", placeholder: "/items/placeholder/glasses/pglasses6.svg", position: { left: 62, top: 142 } },
        { id: 8, itemType: "glasses", src: "/items/glasses/glasses7.svg", placeholder: "/items/placeholder/glasses/pglasses7.svg", position: { left: 65, top: 141 } },
    ],
    hat: [
        { id: 1, itemType: "hat", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/empty.svg", position: { left: 0, top: 0 } },
        { id: 2, itemType: "hat", src: "/items/hat/hat1.svg", placeholder: "/items/hat/hat1.svg", position: { left: 46, top: 64 } },
        { id: 3, itemType: "hat", src: "/items/hat/hat2.svg", placeholder: "/items/hat/hat2.svg", position: { left: 44, top: 115 } },
        { id: 4, itemType: "hat", src: "/items/hat/hat3.svg", placeholder: "/items/hat/hat3.svg", position: { left: 18, top: 50 } },
        { id: 5, itemType: "hat", src: "/items/hat/hat4.svg", placeholder: "/items/hat/hat4.svg", position: { left: 48, top: 50 } },
        { id: 6, itemType: "hat", src: "/items/hat/hat5.svg", placeholder: "/items/hat/hat5.svg", position: { left: 31, top: 40 } },
        { id: 7, itemType: "hat", src: "/items/hat/hat6.svg", placeholder: "/items/hat/hat6.svg", position: { left: 42, top: 55 } },
        { id: 8, itemType: "hat", src: "/items/hat/hat7.svg", placeholder: "/items/hat/hat7.svg", position: { left: 45, top: 0 } },
        { id: 9, itemType: "hat", src: "/items/hat/hat8.svg", placeholder: "/items/hat/hat8.svg", position: { left: 42, top: 100 } },
        { id: 10, itemType: "hat", src: "/items/hat/hat9.svg", placeholder: "/items/hat/hat9.svg", position: { left: 28, top: 28 } },
        { id: 11, itemType: "hat", src: "/items/hat/hat10.svg", placeholder: "/items/hat/hat10.svg", position: { left: 35, top: 12 } },
        { id: 12, itemType: "hat", src: "/items/hat/hat11.svg", placeholder: "/items/hat/hat11.svg", position: { left: 47, top: 16 } },
        { id: 13, itemType: "hat", src: "/items/hat/hat12.svg", placeholder: "/items/hat/hat12.svg", position: { left: 45, top: 20 } },
        { id: 14, itemType: "hat", src: "/items/hat/hat13.svg", placeholder: "/items/hat/hat13.svg", position: { left: 20, top: 35 } },
        { id: 15, itemType: "hat", src: "/items/hat/hat14.svg", placeholder: "/items/hat/hat14.svg", position: { left: 120, top: 70 } },
        { id: 16, itemType: "hat", src: "/items/hat/hat15.svg", placeholder: "/items/hat/hat15.svg", position: { left: 35, top: 20 } },
        { id: 17, itemType: "hat", src: "/items/hat/hat16.svg", placeholder: "/items/hat/hat16.svg", position: { left: 49, top: 40 } },
        { id: 18, itemType: "hat", src: "/items/hat/hat17.svg", placeholder: "/items/hat/hat17.svg", position: { left: 22, top: 12 } },
    ],
    accessory: [
        { id: 1, itemType: "accessory", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/empty.svg", position: { left: 0, top: 0 } },
        { id: 2, itemType: "accessory", src: "/items/accessory/accessory1.svg", placeholder: "/items/accessory/accessory1.svg", position: { left: 105, top: 242 } },
        { id: 3, itemType: "accessory", src: "/items/accessory/accessory2.svg", placeholder: "/items/accessory/accessory2.svg", position: { left: 98, top: 243 } },
        { id: 4, itemType: "accessory", src: "/items/accessory/accessory3.svg", placeholder: "/items/accessory/accessory3.svg", position: { left: 92, top: 238 } },
        { id: 5, itemType: "accessory", src: "/items/accessory/accessory4.svg", placeholder: "/items/accessory/accessory4.svg", position: { left: 31, top: 234 } },
        { id: 6, itemType: "accessory", src: "/items/accessory/accessory5.svg", placeholder: "/items/accessory/accessory5.svg", position: { left: 120, top: 260 } },
        { id: 7, itemType: "accessory", src: "/items/accessory/accessory6.svg", placeholder: "/items/accessory/accessory6.svg", position: { left: 45, top: 170 } },
        { id: 8, itemType: "accessory", src: "/items/accessory/accessory7.svg", placeholder: "/items/accessory/accessory7.svg", position: { left: 16, top: 184 } },
        { id: 9, itemType: "accessory", src: "/items/accessory/accessory8.svg", placeholder: "/items/accessory/accessory8.svg", position: { left: 42, top: 160 } },
        //{ id: 10, itemType: "accessory", src: "/items/accessory/accessory9.svg", placeholder: "/items/accessory/accessory9.svg", position: { left: 0, top: 0 } },
    ],
    outfit: [
        { id: 1, itemType: "outfit", src: "/items/outfit/foutfit1.svg", position: { left: 15, top: 230 } },
        { id: 2, itemType: "outfit", src: "/items/outfit/foutfit2.svg", position: { left: 15, top: 230 } },
        { id: 3, itemType: "outfit", src: "/items/outfit/foutfit3.svg", position: { left: 15, top: 230 } },
    ],
};