export const ITEMS_MALE = {
    head: [
        { id: 1, itemType: "head", src: "/items/head/head1.svg", position: { left: 50, top: 40 } },
        { id: 2, itemType: "head", src: "/items/head/head2.svg", position: { left: 50, top: 40 } },
        { id: 3, itemType: "head", src: "/items/head/head3.svg", position: { left: 50, top: 40 } },
        { id: 4, itemType: "head", src: "/items/head/head4.svg", position: { left: 37, top: 40 } },
        { id: 5, itemType: "head", src: "/items/head/head5.svg", position: { left: 28, top: 40 } },
    ],
    makeup: [
        { id: 1, itemType: "makeup", src: "/items/placeholder/empty.svg", position: { left: 56, top: 131 } },
        { id: 2, itemType: "makeup", src: "/items/makeup/makeup1.svg", position: { left: 56, top: 131 } },
        { id: 3, itemType: "makeup", src: "/items/makeup/makeup2.svg", position: { left: 56, top: 131 } },
        { id: 4, itemType: "makeup", src: "/items/makeup/makeup3.svg", position: { left: 49, top: 88 } },
        { id: 5, itemType: "makeup", src: "/items/makeup/makeup4.svg", position: { left: 54, top: 88 } },
        { id: 6, itemType: "makeup", src: "/items/makeup/makeup5.svg", position: { left: 72, top: 140 } },
    ],
    wrinkles: [
        { id: 1, itemType: "wrinkles", src: "/items/placeholder/empty.svg", position: { left: 57, top: 125 } },
        { id: 2, itemType: "wrinkles", src: "/items/wrinkles/wrinkles1.svg", position: { left: 57, top: 122 } },
        { id: 3, itemType: "wrinkles", src: "/items/wrinkles/wrinkles2.svg", position: { left: 82, top: 122 } },
        { id: 4, itemType: "wrinkles", src: "/items/wrinkles/wrinkles3.svg", position: { left: 65, top: 146 } },
        { id: 5, itemType: "wrinkles", src: "/items/wrinkles/wrinkles4.svg", position: { left: 53, top: 112 } },
        { id: 6, itemType: "wrinkles", src: "/items/wrinkles/wrinkles5.svg", position: { left: 58, top: 130 } },
        { id: 7, itemType: "wrinkles", src: "/items/wrinkles/wrinkles6.svg", position: { left: 103, top: 185 } },
    ],
    hair: [
        { id: 1, itemType: "hair", src: "/items/hair/mhair1.svg", placeholder: "/items/placeholder/hair/mphair1.svg", position: { left: 42, top: 25 } },
        { id: 2, itemType: "hair", src: "/items/hair/mhair2.svg", placeholder: "/items/placeholder/hair/mphair2.svg", position: { left: 36, top: 17 } },
        { id: 3, itemType: "hair", src: "/items/hair/mhair3.svg", placeholder: "/items/placeholder/hair/mphair3.svg", position: { left: 42, top: 25 } },
        { id: 4, itemType: "hair", src: "/items/hair/mhair4.svg", placeholder: "/items/placeholder/hair/mphair4.svg", position: { left: 42, top: 25 } },
        { id: 5, itemType: "hair", src: "/items/hair/mhair5.svg", placeholder: "/items/placeholder/hair/mphair5.svg", position: { left: 42, top: 25 } },
        { id: 6, itemType: "hair", src: "/items/hair/mhair6.svg", placeholder: "/items/placeholder/hair/mphair6.svg", position: { left: 43, top: 12 } },
        { id: 7, itemType: "hair", src: "/items/hair/mhair7.svg", placeholder: "/items/placeholder/hair/mphair7.svg", position: { left: 42, top: 12 } },
        { id: 8, itemType: "hair", src: "/items/hair/mhair8.svg", placeholder: "/items/placeholder/hair/mphair8.svg", position: { left: 42, top: 25 } },
        { id: 9, itemType: "hair", src: "/items/hair/mhair9.svg", placeholder: "/items/placeholder/hair/mphair9.svg", position: { left: 42, top: 26 } },
        { id: 10, itemType: "hair", src: "/items/hair/mhair10.svg", placeholder: "/items/placeholder/hair/mphair10.svg", position: { left: 42, top: 25 } },
        { id: 11, itemType: "hair", src: "/items/hair/mhair11.svg", placeholder: "/items/placeholder/hair/mphair11.svg", position: { left: 24, top: 7 } },
        { id: 12, itemType: "hair", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/empty.svg", position: { left: 42, top: 25 } },
    ],
    eyebrows: [
        { id: 1, itemType: "eyebrows", src: "/items/eyebrows/eyebrows1.svg", placeholder: "/items/placeholder/eyebrows/peyebrows1.svg", position: { left: 67, top: 90 } },
        { id: 2, itemType: "eyebrows", src: "/items/eyebrows/eyebrows2.svg", placeholder: "/items/placeholder/eyebrows/peyebrows2.svg", position: { left: 67, top: 93 } },
        { id: 3, itemType: "eyebrows", src: "/items/eyebrows/eyebrows3.svg", placeholder: "/items/placeholder/eyebrows/peyebrows3.svg", position: { left: 66, top: 90 } },
        { id: 4, itemType: "eyebrows", src: "/items/eyebrows/eyebrows4.svg", placeholder: "/items/placeholder/eyebrows/peyebrows4.svg", position: { left: 69, top: 92 } },
        { id: 5, itemType: "eyebrows", src: "/items/eyebrows/eyebrows5.svg", placeholder: "/items/placeholder/eyebrows/peyebrows5.svg", position: { left: 72, top: 91 } },
        { id: 6, itemType: "eyebrows", src: "/items/eyebrows/eyebrows6.svg", placeholder: "/items/placeholder/eyebrows/peyebrows6.svg", position: { left: 68, top: 95 } },
        { id: 7, itemType: "eyebrows", src: "/items/eyebrows/eyebrows7.svg", placeholder: "/items/placeholder/eyebrows/peyebrows7.svg", position: { left: 71, top: 93 } },
        { id: 8, itemType: "eyebrows", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/empty.svg", position: { left: 0, top: 0 } },
        { id: 9, itemType: "eyebrows", src: "/items/eyebrows/eyebrows9.svg", placeholder: "/items/placeholder/eyebrows/peyebrows9.svg", position: { left: 68, top: 93 } },
    ],
    eyes: [
        { id: 1, itemType: "eyes", src: "/items/eyes/eyes1.svg", placeholder: "/items/placeholder/eyes/peyes1.svg", position: { left: 67, top: 108 } },
        { id: 2, itemType: "eyes", src: "/items/eyes/eyes2.svg", placeholder: "/items/placeholder/eyes/peyes2.svg", position: { left: 61, top: 107 } },
        { id: 3, itemType: "eyes", src: "/items/eyes/eyes3.svg", placeholder: "/items/placeholder/eyes/peyes3.svg", position: { left: 63, top: 104 } },
        { id: 4, itemType: "eyes", src: "/items/eyes/eyes4.svg", placeholder: "/items/placeholder/eyes/peyes4.svg", position: { left: 71, top: 103 } },
        { id: 5, itemType: "eyes", src: "/items/eyes/eyes5.svg", placeholder: "/items/placeholder/eyes/peyes5.svg", position: { left: 71, top: 106 } },
        { id: 6, itemType: "eyes", src: "/items/eyes/eyes6.svg", placeholder: "/items/placeholder/eyes/peyes6.svg", position: { left: 69, top: 110 } },
        { id: 7, itemType: "eyes", src: "/items/eyes/eyes7.svg", placeholder: "/items/placeholder/eyes/peyes7.svg", position: { left: 74, top: 105 } },
        { id: 8, itemType: "eyes", src: "/items/eyes/eyes8.svg", placeholder: "/items/placeholder/eyes/peyes8.svg", position: { left: 72, top: 106 } },
        { id: 9, itemType: "eyes", src: "/items/eyes/eyes9.svg", placeholder: "/items/placeholder/eyes/peyes9.svg", position: { left: 72, top: 103 } },
        { id: 10, itemType: "eyes", src: "/items/eyes/eyes10.svg", placeholder: "/items/placeholder/eyes/peyes10.svg", position: { left: 73, top: 108 } },
        { id: 11, itemType: "eyes", src: "/items/eyes/eyes11.svg", placeholder: "/items/placeholder/eyes/peyes11.svg", position: { left: 70, top: 108 } },
        { id: 12, itemType: "eyes", src: "/items/eyes/eyes12.svg", placeholder: "/items/placeholder/eyes/peyes12.svg", position: { left: 73, top: 108 } },
        { id: 13, itemType: "eyes", src: "/items/eyes/eyes13.svg", placeholder: "/items/placeholder/eyes/peyes13.svg", position: { left: 74, top: 115 } },
        { id: 14, itemType: "eyes", src: "/items/eyes/eyes14.svg", placeholder: "/items/placeholder/eyes/peyes14.svg", position: { left: 62, top: 110 } },
        { id: 15, itemType: "eyes", src: "/items/eyes/eyes15.svg", placeholder: "/items/placeholder/eyes/peyes15.svg", position: { left: 62, top: 110 } },
        { id: 16, itemType: "eyes", src: "/items/eyes/eyes16.svg", placeholder: "/items/placeholder/eyes/peyes16.svg", position: { left: 69, top: 108 } },
        { id: 17, itemType: "eyes", src: "/items/eyes/eyes17.svg", placeholder: "/items/placeholder/eyes/peyes17.svg", position: { left: 65, top: 107 } },
        { id: 18, itemType: "eyes", src: "/items/eyes/eyes18.svg", placeholder: "/items/placeholder/eyes/peyes18.svg", position: { left: 68, top: 106 } },
        { id: 19, itemType: "eyes", src: "/items/eyes/eyes19.svg", placeholder: "/items/placeholder/eyes/peyes19.svg", position: { left: 66, top: 107 } },
        { id: 20, itemType: "eyes", src: "/items/eyes/eyes20.svg", placeholder: "/items/placeholder/eyes/peyes20.svg", position: { left: 66, top: 92 } },
        { id: 21, itemType: "eyes", src: "/items/eyes/eyes21.svg", placeholder: "/items/placeholder/eyes/peyes21.svg", position: { left: 58, top: 82 } },
        { id: 22, itemType: "eyes", src: "/items/eyes/eyes22.svg", placeholder: "/items/placeholder/eyes/peyes22.svg", position: { left: 75, top: 108 } },
        { id: 23, itemType: "eyes", src: "/items/eyes/eyes23.svg", placeholder: "/items/placeholder/eyes/peyes23.svg", position: { left: 59, top: 103 } },
        { id: 24, itemType: "eyes", src: "/items/eyes/eyes24.svg", placeholder: "/items/placeholder/eyes/peyes24.svg", position: { left: 72, top: 104 } },
    ],
    nose: [
        { id: 1, itemType: "nose", src: "/items/nose/nose1.svg", placeholder: "/items/placeholder/nose/pnose1.svg", position: { left: 106, top: 125 } },
        { id: 2, itemType: "nose", src: "/items/nose/nose2.svg", placeholder: "/items/placeholder/nose/pnose2.svg", position: { left: 103, top: 144 } },
        { id: 3, itemType: "nose", src: "/items/nose/nose3.svg", placeholder: "/items/placeholder/nose/pnose3.svg", position: { left: 106, top: 142 } },
        { id: 4, itemType: "nose", src: "/items/nose/nose4.svg", placeholder: "/items/placeholder/nose/pnose4.svg", position: { left: 102, top: 142 } },
        { id: 5, itemType: "nose", src: "/items/nose/nose5.svg", placeholder: "/items/placeholder/nose/pnose5.svg", position: { left: 108, top: 141 } },
        { id: 6, itemType: "nose", src: "/items/nose/nose6.svg", placeholder: "/items/placeholder/nose/pnose6.svg", position: { left: 101, top: 139 } },
        { id: 7, itemType: "nose", src: "/items/nose/nose7.svg", placeholder: "/items/placeholder/nose/pnose7.svg", position: { left: 102, top: 138 } },
        { id: 8, itemType: "nose", src: "/items/nose/nose8.svg", placeholder: "/items/placeholder/nose/pnose8.svg", position: { left: 106, top: 134 } },
        { id: 9, itemType: "nose", src: "/items/nose/nose9.svg", placeholder: "/items/placeholder/nose/pnose9.svg", position: { left: 101, top: 129 } },
        { id: 10, itemType: "nose", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/empty.svg", position: { left: 0, top: 0 } },
        { id: 11, itemType: "nose", src: "/items/nose/nose11.svg", placeholder: "/items/placeholder/nose/pnose11.svg", position: { left: 103, top: 133 } },
        { id: 12, itemType: "nose", src: "/items/nose/nose12.svg", placeholder: "/items/placeholder/nose/pnose12.svg", position: { left: 109, top: 127 } },
    ],
    mouth: [
        { id: 1, itemType: "mouth", src: "/items/mouth/mouth1.svg", placeholder: "/items/placeholder/mouth/pmouth1.svg", position: { left: 103, top: 173 } },
        { id: 2, itemType: "mouth", src: "/items/mouth/mouth2.svg", placeholder: "/items/placeholder/mouth/pmouth2.svg", position: { left: 97, top: 171 } },
        { id: 3, itemType: "mouth", src: "/items/mouth/mouth3.svg", placeholder: "/items/placeholder/mouth/pmouth3.svg", position: { left: 97, top: 170 } },
        { id: 4, itemType: "mouth", src: "/items/mouth/mouth4.svg", placeholder: "/items/placeholder/mouth/pmouth4.svg", position: { left: 96, top: 171 } },
        { id: 5, itemType: "mouth", src: "/items/mouth/mouth5.svg", placeholder: "/items/placeholder/mouth/pmouth5.svg", position: { left: 96, top: 170 } },
        { id: 6, itemType: "mouth", src: "/items/mouth/mouth6.svg", placeholder: "/items/placeholder/mouth/pmouth6.svg", position: { left: 95, top: 173 } },
        { id: 7, itemType: "mouth", src: "/items/mouth/mouth7.svg", placeholder: "/items/placeholder/mouth/pmouth7.svg", position: { left: 95, top: 168 } },
        { id: 8, itemType: "mouth", src: "/items/mouth/mouth8.svg", placeholder: "/items/placeholder/mouth/pmouth8.svg", position: { left: 101, top: 168 } },
        { id: 9, itemType: "mouth", src: "/items/mouth/mouth9.svg", placeholder: "/items/placeholder/mouth/pmouth9.svg", position: { left: 107, top: 167 } },
        { id: 10, itemType: "mouth", src: "/items/mouth/mouth10.svg", placeholder: "/items/placeholder/mouth/pmouth10.svg", position: { left: 95, top: 166 } },
        { id: 11, itemType: "mouth", src: "/items/mouth/mouth11.svg", placeholder: "/items/placeholder/mouth/pmouth11.svg", position: { left: 98, top: 172 } },
        { id: 12, itemType: "mouth", src: "/items/mouth/mouth12.svg", placeholder: "/items/placeholder/mouth/pmouth12.svg", position: { left: 98, top: 172 } },
        { id: 13, itemType: "mouth", src: "/items/mouth/mouth13.svg", placeholder: "/items/placeholder/mouth/pmouth13.svg", position: { left: 101, top: 168 } },
        { id: 14, itemType: "mouth", src: "/items/mouth/mouth14.svg", placeholder: "/items/placeholder/mouth/pmouth14.svg", position: { left: 103, top: 167 } },
        { id: 15, itemType: "mouth", src: "/items/mouth/mouth15.svg", placeholder: "/items/placeholder/mouth/pmouth15.svg", position: { left: 93, top: 165 } },
        { id: 16, itemType: "mouth", src: "/items/mouth/mouth16.svg", placeholder: "/items/placeholder/mouth/pmouth16.svg", position: { left: 107, top: 172 } },
        { id: 17, itemType: "mouth", src: "/items/mouth/mouth17.svg", placeholder: "/items/placeholder/mouth/pmouth17.svg", position: { left: 101, top: 168 } },
        { id: 18, itemType: "mouth", src: "/items/mouth/mouth18.svg", placeholder: "/items/placeholder/mouth/pmouth18.svg", position: { left: 102, top: 170 } },
        { id: 19, itemType: "mouth", src: "/items/mouth/mouth19.svg", placeholder: "/items/placeholder/mouth/pmouth19.svg", position: { left: 112, top: 166 } },
        { id: 20, itemType: "mouth", src: "/items/mouth/mouth20.svg", placeholder: "/items/placeholder/mouth/pmouth20.svg", position: { left: 96, top: 169 } },
        { id: 21, itemType: "mouth", src: "/items/mouth/mouth21.svg", placeholder: "/items/placeholder/mouth/pmouth21.svg", position: { left: 98, top: 167 } },
        { id: 22, itemType: "mouth", src: "/items/mouth/mouth22.svg", placeholder: "/items/placeholder/mouth/pmouth22.svg", position: { left: 82, top: 168 } },
        { id: 23, itemType: "mouth", src: "/items/mouth/mouth23.svg", placeholder: "/items/placeholder/mouth/pmouth23.svg", position: { left: 88, top: 169 } },
        { id: 24, itemType: "mouth", src: "/items/mouth/mouth24.svg", placeholder: "/items/placeholder/mouth/pmouth24.svg", position: { left: 76, top: 165 } },
    ],
    glasses: [
        { id: 1, itemType: "glasses", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/glasses/empty-head.svg", position: { left: 65, top: 103 } },
        { id: 2, itemType: "glasses", src: "/items/glasses/glasses1.svg", placeholder: "/items/placeholder/glasses/pglasses1.svg", position: { left: 64, top: 103 } },
        { id: 3, itemType: "glasses", src: "/items/glasses/glasses2.svg", placeholder: "/items/placeholder/glasses/pglasses2.svg", position: { left: 63, top: 105 } },
        { id: 4, itemType: "glasses", src: "/items/glasses/glasses3.svg", placeholder: "/items/placeholder/glasses/pglasses3.svg", position: { left: 65, top: 98 } },
        { id: 5, itemType: "glasses", src: "/items/glasses/glasses4.svg", placeholder: "/items/placeholder/glasses/pglasses4.svg", position: { left: 58, top: 100 } },
        { id: 6, itemType: "glasses", src: "/items/glasses/glasses5.svg", placeholder: "/items/placeholder/glasses/pglasses5.svg", position: { left: 63, top: 103 } },
        { id: 7, itemType: "glasses", src: "/items/glasses/glasses6.svg", placeholder: "/items/placeholder/glasses/pglasses6.svg", position: { left: 62, top: 102 } },
        { id: 8, itemType: "glasses", src: "/items/glasses/glasses7.svg", placeholder: "/items/placeholder/glasses/pglasses7.svg", position: { left: 65, top: 101 } },
    ],
    outfit: [
        { id: 1, itemType: "outfit", src: "/items/outfit/moutfit1.svg", position: { left: 15, top: 190 } },
        { id: 2, itemType: "outfit", src: "/items/outfit/moutfit2.svg", position: { left: 15, top: 190 } },
        { id: 3, itemType: "outfit", src: "/items/outfit/moutfit3.svg", position: { left: 15, top: 190 } },
    ],
    beard: [
        { id: 1, itemType: "beard", src: "/items/beard/beard1.svg", position: { left: 0, top: 0 } },
        { id: 2, itemType: "beard", src: "/items/beard/beard2.svg", position: { left: 0, top: 0 } },
        { id: 3, itemType: "beard", src: "/items/beard/beard3.svg", position: { left: 0, top: 0 } },
        { id: 4, itemType: "beard", src: "/items/beard/beard4.svg", position: { left: 0, top: 0 } },
    ],
};

export const ITEMS_FEMALE = {
    head: [
        { id: 1, itemType: "head", src: "/items/head/head1.svg", position: { left: 50, top: 40 } },
        { id: 2, itemType: "head", src: "/items/head/head2.svg", position: { left: 50, top: 40 } },
        { id: 3, itemType: "head", src: "/items/head/head3.svg", position: { left: 50, top: 40 } },
        { id: 4, itemType: "head", src: "/items/head/head4.svg", position: { left: 37, top: 40 } },
        { id: 5, itemType: "head", src: "/items/head/head5.svg", position: { left: 28, top: 40 } },
    ],
    makeup: [
        { id: 1, itemType: "makeup", src: "/items/placeholder/empty.svg", position: { left: 56, top: 131 } },
        { id: 2, itemType: "makeup", src: "/items/makeup/makeup1.svg", position: { left: 56, top: 131 } },
        { id: 3, itemType: "makeup", src: "/items/makeup/makeup2.svg", position: { left: 56, top: 131 } },
        { id: 4, itemType: "makeup", src: "/items/makeup/makeup3.svg", position: { left: 49, top: 88 } },
        { id: 5, itemType: "makeup", src: "/items/makeup/makeup4.svg", position: { left: 54, top: 88 } },
        { id: 6, itemType: "makeup", src: "/items/makeup/makeup5.svg", position: { left: 72, top: 140 } },
    ],
    wrinkles: [
        { id: 1, itemType: "wrinkles", src: "/items/placeholder/empty.svg", position: { left: 57, top: 125 } },
        { id: 2, itemType: "wrinkles", src: "/items/wrinkles/wrinkles1.svg", position: { left: 57, top: 122 } },
        { id: 3, itemType: "wrinkles", src: "/items/wrinkles/wrinkles2.svg", position: { left: 82, top: 122 } },
        { id: 4, itemType: "wrinkles", src: "/items/wrinkles/wrinkles3.svg", position: { left: 65, top: 146 } },
        { id: 5, itemType: "wrinkles", src: "/items/wrinkles/wrinkles4.svg", position: { left: 53, top: 112 } },
        { id: 6, itemType: "wrinkles", src: "/items/wrinkles/wrinkles5.svg", position: { left: 58, top: 130 } },
        { id: 7, itemType: "wrinkles", src: "/items/wrinkles/wrinkles6.svg", position: { left: 103, top: 185 } },
    ],
    hair: [
        { id: 1, itemType: "hair", src: "/items/hair/fhair1.svg", placeholder: "/items/placeholder/hair/fphair1.svg", position: { left: 35, top: 16 } },
        { id: 2, itemType: "hair", src: "/items/hair/fhair2.svg", placeholder: "/items/placeholder/hair/fphair2.svg", position: { left: 35, top: 16 } },
        { id: 3, itemType: "hair", src: "/items/hair/fhair3.svg", placeholder: "/items/placeholder/hair/fphair3.svg", position: { left: 35, top: 16 } },
        { id: 4, itemType: "hair", src: "/items/hair/fhair4.svg", placeholder: "/items/placeholder/hair/fphair4.svg", position: { left: 35, top: 16 } },
        { id: 5, itemType: "hair", src: "/items/hair/fhair5.svg", placeholder: "/items/placeholder/hair/fphair5.svg", position: { left: 35, top: 16 } },
        { id: 6, itemType: "hair", src: "/items/hair/fhair6.svg", placeholder: "/items/placeholder/hair/fphair6.svg", position: { left: 35, top: 16 } },
        { id: 7, itemType: "hair", src: "/items/hair/fhair7.svg", placeholder: "/items/placeholder/hair/fphair7.svg", position: { left: 35, top: 16 } },
        { id: 8, itemType: "hair", src: "/items/hair/fhair8.svg", placeholder: "/items/placeholder/hair/fphair8.svg", position: { left: 35, top: 16 } },
        { id: 9, itemType: "hair", src: "/items/hair/fhair9.svg", placeholder: "/items/placeholder/hair/fphair9.svg", position: { left: 35, top: 16 } },
        { id: 10, itemType: "hair", src: "/items/hair/fhair10.svg", placeholder: "/items/placeholder/hair/fphair10.svg", position: { left: 35, top: 16 } },
        { id: 11, itemType: "hair", src: "/items/hair/fhair11.svg", placeholder: "/items/placeholder/hair/fphair11.svg", position: { left: 35, top: 16 } },
        { id: 12, itemType: "hair", src: "/items/hair/fhair12.svg", placeholder: "/items/placeholder/hair/fphair12.svg", position: { left: 35, top: 16 } },
        { id: 13, itemType: "hair", src: "/items/hair/fhair13.svg", placeholder: "/items/placeholder/hair/fphair13.svg", position: { left: 35, top: 16 } },
        { id: 14, itemType: "hair", src: "/items/hair/fhair14.svg", placeholder: "/items/placeholder/hair/fphair14.svg", position: { left: 35, top: 16 } },
        { id: 15, itemType: "hair", src: "/items/hair/fhair15.svg", placeholder: "/items/placeholder/hair/fphair15.svg", position: { left: 35, top: 16 } },
        { id: 16, itemType: "hair", src: "/items/hair/fhair16.svg", placeholder: "/items/placeholder/hair/fphair16.svg", position: { left: 35, top: 16 } },
        { id: 17, itemType: "hair", src: "/items/hair/fhair17.svg", placeholder: "/items/placeholder/hair/fphair17.svg", position: { left: 35, top: 16 } },
        { id: 18, itemType: "hair", src: "/items/hair/fhair18.svg", placeholder: "/items/placeholder/hair/fphair18.svg", position: { left: 35, top: 16 } },
        { id: 19, itemType: "hair", src: "/items/hair/fhair19.svg", placeholder: "/items/placeholder/hair/fphair19.svg", position: { left: 35, top: 16 } },
        { id: 16, itemType: "hair", src: "/items/hair/fhair16.svg", placeholder: "/items/placeholder/hair/fphair16.svg", position: { left: 35, top: 16 } },
        { id: 21, itemType: "hair", src: "/items/hair/fhair21.svg", placeholder: "/items/placeholder/hair/fphair21.svg", position: { left: 35, top: 16 } },
    ],
    eyebrows: [
        { id: 1, itemType: "eyebrows", src: "/items/eyebrows/eyebrows1.svg", placeholder: "/items/placeholder/eyebrows/peyebrows1.svg", position: { left: 67, top: 90 } },
        { id: 2, itemType: "eyebrows", src: "/items/eyebrows/eyebrows2.svg", placeholder: "/items/placeholder/eyebrows/peyebrows2.svg", position: { left: 67, top: 93 } },
        { id: 3, itemType: "eyebrows", src: "/items/eyebrows/eyebrows3.svg", placeholder: "/items/placeholder/eyebrows/peyebrows3.svg", position: { left: 66, top: 90 } },
        { id: 4, itemType: "eyebrows", src: "/items/eyebrows/eyebrows4.svg", placeholder: "/items/placeholder/eyebrows/peyebrows4.svg", position: { left: 69, top: 92 } },
        { id: 5, itemType: "eyebrows", src: "/items/eyebrows/eyebrows5.svg", placeholder: "/items/placeholder/eyebrows/peyebrows5.svg", position: { left: 72, top: 91 } },
        { id: 6, itemType: "eyebrows", src: "/items/eyebrows/eyebrows6.svg", placeholder: "/items/placeholder/eyebrows/peyebrows6.svg", position: { left: 68, top: 95 } },
        { id: 7, itemType: "eyebrows", src: "/items/eyebrows/eyebrows7.svg", placeholder: "/items/placeholder/eyebrows/peyebrows7.svg", position: { left: 71, top: 93 } },
        { id: 8, itemType: "eyebrows", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/empty.svg", position: { left: 0, top: 0 } },
        { id: 9, itemType: "eyebrows", src: "/items/eyebrows/eyebrows9.svg", placeholder: "/items/placeholder/eyebrows/peyebrows9.svg", position: { left: 68, top: 93 } },
    ],
    eyes: [
        { id: 1, itemType: "eyes", src: "/items/eyes/eyes1.svg", placeholder: "/items/placeholder/eyes/peyes1.svg", position: { left: 67, top: 108 } },
        { id: 2, itemType: "eyes", src: "/items/eyes/eyes2.svg", placeholder: "/items/placeholder/eyes/peyes2.svg", position: { left: 61, top: 107 } },
        { id: 3, itemType: "eyes", src: "/items/eyes/eyes3.svg", placeholder: "/items/placeholder/eyes/peyes3.svg", position: { left: 63, top: 104 } },
        { id: 4, itemType: "eyes", src: "/items/eyes/eyes4.svg", placeholder: "/items/placeholder/eyes/peyes4.svg", position: { left: 71, top: 103 } },
        { id: 5, itemType: "eyes", src: "/items/eyes/eyes5.svg", placeholder: "/items/placeholder/eyes/peyes5.svg", position: { left: 71, top: 106 } },
        { id: 6, itemType: "eyes", src: "/items/eyes/eyes6.svg", placeholder: "/items/placeholder/eyes/peyes6.svg", position: { left: 69, top: 110 } },
        { id: 7, itemType: "eyes", src: "/items/eyes/eyes7.svg", placeholder: "/items/placeholder/eyes/peyes7.svg", position: { left: 74, top: 105 } },
        { id: 8, itemType: "eyes", src: "/items/eyes/eyes8.svg", placeholder: "/items/placeholder/eyes/peyes8.svg", position: { left: 72, top: 106 } },
        { id: 9, itemType: "eyes", src: "/items/eyes/eyes9.svg", placeholder: "/items/placeholder/eyes/peyes9.svg", position: { left: 72, top: 103 } },
        { id: 10, itemType: "eyes", src: "/items/eyes/eyes10.svg", placeholder: "/items/placeholder/eyes/peyes10.svg", position: { left: 73, top: 108 } },
        { id: 11, itemType: "eyes", src: "/items/eyes/eyes11.svg", placeholder: "/items/placeholder/eyes/peyes11.svg", position: { left: 70, top: 108 } },
        { id: 12, itemType: "eyes", src: "/items/eyes/eyes12.svg", placeholder: "/items/placeholder/eyes/peyes12.svg", position: { left: 73, top: 108 } },
        { id: 13, itemType: "eyes", src: "/items/eyes/eyes13.svg", placeholder: "/items/placeholder/eyes/peyes13.svg", position: { left: 74, top: 115 } },
        { id: 14, itemType: "eyes", src: "/items/eyes/eyes14.svg", placeholder: "/items/placeholder/eyes/peyes14.svg", position: { left: 62, top: 110 } },
        { id: 15, itemType: "eyes", src: "/items/eyes/eyes15.svg", placeholder: "/items/placeholder/eyes/peyes15.svg", position: { left: 62, top: 110 } },
        { id: 16, itemType: "eyes", src: "/items/eyes/eyes16.svg", placeholder: "/items/placeholder/eyes/peyes16.svg", position: { left: 69, top: 108 } },
        { id: 17, itemType: "eyes", src: "/items/eyes/eyes17.svg", placeholder: "/items/placeholder/eyes/peyes17.svg", position: { left: 65, top: 107 } },
        { id: 18, itemType: "eyes", src: "/items/eyes/eyes18.svg", placeholder: "/items/placeholder/eyes/peyes18.svg", position: { left: 68, top: 106 } },
        { id: 19, itemType: "eyes", src: "/items/eyes/eyes19.svg", placeholder: "/items/placeholder/eyes/peyes19.svg", position: { left: 66, top: 107 } },
        { id: 20, itemType: "eyes", src: "/items/eyes/eyes20.svg", placeholder: "/items/placeholder/eyes/peyes20.svg", position: { left: 66, top: 92 } },
        { id: 21, itemType: "eyes", src: "/items/eyes/eyes21.svg", placeholder: "/items/placeholder/eyes/peyes21.svg", position: { left: 58, top: 82 } },
        { id: 22, itemType: "eyes", src: "/items/eyes/eyes22.svg", placeholder: "/items/placeholder/eyes/peyes22.svg", position: { left: 75, top: 108 } },
        { id: 23, itemType: "eyes", src: "/items/eyes/eyes23.svg", placeholder: "/items/placeholder/eyes/peyes23.svg", position: { left: 59, top: 103 } },
        { id: 24, itemType: "eyes", src: "/items/eyes/eyes24.svg", placeholder: "/items/placeholder/eyes/peyes24.svg", position: { left: 72, top: 104 } },
    ],
    nose: [
        { id: 1, itemType: "nose", src: "/items/nose/nose1.svg", placeholder: "/items/placeholder/nose/pnose1.svg", position: { left: 106, top: 125 } },
        { id: 2, itemType: "nose", src: "/items/nose/nose2.svg", placeholder: "/items/placeholder/nose/pnose2.svg", position: { left: 103, top: 144 } },
        { id: 3, itemType: "nose", src: "/items/nose/nose3.svg", placeholder: "/items/placeholder/nose/pnose3.svg", position: { left: 106, top: 142 } },
        { id: 4, itemType: "nose", src: "/items/nose/nose4.svg", placeholder: "/items/placeholder/nose/pnose4.svg", position: { left: 102, top: 142 } },
        { id: 5, itemType: "nose", src: "/items/nose/nose5.svg", placeholder: "/items/placeholder/nose/pnose5.svg", position: { left: 108, top: 141 } },
        { id: 6, itemType: "nose", src: "/items/nose/nose6.svg", placeholder: "/items/placeholder/nose/pnose6.svg", position: { left: 101, top: 139 } },
        { id: 7, itemType: "nose", src: "/items/nose/nose7.svg", placeholder: "/items/placeholder/nose/pnose7.svg", position: { left: 102, top: 138 } },
        { id: 8, itemType: "nose", src: "/items/nose/nose8.svg", placeholder: "/items/placeholder/nose/pnose8.svg", position: { left: 106, top: 134 } },
        { id: 9, itemType: "nose", src: "/items/nose/nose9.svg", placeholder: "/items/placeholder/nose/pnose9.svg", position: { left: 101, top: 129 } },
        { id: 10, itemType: "nose", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/empty.svg", position: { left: 0, top: 0 } },
        { id: 11, itemType: "nose", src: "/items/nose/nose11.svg", placeholder: "/items/placeholder/nose/pnose11.svg", position: { left: 103, top: 133 } },
        { id: 12, itemType: "nose", src: "/items/nose/nose12.svg", placeholder: "/items/placeholder/nose/pnose12.svg", position: { left: 109, top: 127 } },
    ],
    mouth: [
        { id: 1, itemType: "mouth", src: "/items/mouth/mouth1.svg", placeholder: "/items/placeholder/mouth/pmouth1.svg", position: { left: 103, top: 173 } },
        { id: 2, itemType: "mouth", src: "/items/mouth/mouth2.svg", placeholder: "/items/placeholder/mouth/pmouth2.svg", position: { left: 97, top: 171 } },
        { id: 3, itemType: "mouth", src: "/items/mouth/mouth3.svg", placeholder: "/items/placeholder/mouth/pmouth3.svg", position: { left: 97, top: 170 } },
        { id: 4, itemType: "mouth", src: "/items/mouth/mouth4.svg", placeholder: "/items/placeholder/mouth/pmouth4.svg", position: { left: 96, top: 171 } },
        { id: 5, itemType: "mouth", src: "/items/mouth/mouth5.svg", placeholder: "/items/placeholder/mouth/pmouth5.svg", position: { left: 96, top: 170 } },
        { id: 6, itemType: "mouth", src: "/items/mouth/mouth6.svg", placeholder: "/items/placeholder/mouth/pmouth6.svg", position: { left: 95, top: 173 } },
        { id: 7, itemType: "mouth", src: "/items/mouth/mouth7.svg", placeholder: "/items/placeholder/mouth/pmouth7.svg", position: { left: 95, top: 168 } },
        { id: 8, itemType: "mouth", src: "/items/mouth/mouth8.svg", placeholder: "/items/placeholder/mouth/pmouth8.svg", position: { left: 101, top: 168 } },
        { id: 9, itemType: "mouth", src: "/items/mouth/mouth9.svg", placeholder: "/items/placeholder/mouth/pmouth9.svg", position: { left: 107, top: 167 } },
        { id: 10, itemType: "mouth", src: "/items/mouth/mouth10.svg", placeholder: "/items/placeholder/mouth/pmouth10.svg", position: { left: 95, top: 166 } },
        { id: 11, itemType: "mouth", src: "/items/mouth/mouth11.svg", placeholder: "/items/placeholder/mouth/pmouth11.svg", position: { left: 98, top: 172 } },
        { id: 12, itemType: "mouth", src: "/items/mouth/mouth12.svg", placeholder: "/items/placeholder/mouth/pmouth12.svg", position: { left: 98, top: 172 } },
        { id: 13, itemType: "mouth", src: "/items/mouth/mouth13.svg", placeholder: "/items/placeholder/mouth/pmouth13.svg", position: { left: 101, top: 168 } },
        { id: 14, itemType: "mouth", src: "/items/mouth/mouth14.svg", placeholder: "/items/placeholder/mouth/pmouth14.svg", position: { left: 103, top: 167 } },
        { id: 15, itemType: "mouth", src: "/items/mouth/mouth15.svg", placeholder: "/items/placeholder/mouth/pmouth15.svg", position: { left: 93, top: 165 } },
        { id: 16, itemType: "mouth", src: "/items/mouth/mouth16.svg", placeholder: "/items/placeholder/mouth/pmouth16.svg", position: { left: 107, top: 172 } },
        { id: 17, itemType: "mouth", src: "/items/mouth/mouth17.svg", placeholder: "/items/placeholder/mouth/pmouth17.svg", position: { left: 101, top: 168 } },
        { id: 18, itemType: "mouth", src: "/items/mouth/mouth18.svg", placeholder: "/items/placeholder/mouth/pmouth18.svg", position: { left: 102, top: 170 } },
        { id: 19, itemType: "mouth", src: "/items/mouth/mouth19.svg", placeholder: "/items/placeholder/mouth/pmouth19.svg", position: { left: 112, top: 166 } },
        { id: 20, itemType: "mouth", src: "/items/mouth/mouth20.svg", placeholder: "/items/placeholder/mouth/pmouth20.svg", position: { left: 96, top: 169 } },
        { id: 21, itemType: "mouth", src: "/items/mouth/mouth21.svg", placeholder: "/items/placeholder/mouth/pmouth21.svg", position: { left: 98, top: 167 } },
        { id: 22, itemType: "mouth", src: "/items/mouth/mouth22.svg", placeholder: "/items/placeholder/mouth/pmouth22.svg", position: { left: 82, top: 168 } },
        { id: 23, itemType: "mouth", src: "/items/mouth/mouth23.svg", placeholder: "/items/placeholder/mouth/pmouth23.svg", position: { left: 88, top: 169 } },
        { id: 24, itemType: "mouth", src: "/items/mouth/mouth24.svg", placeholder: "/items/placeholder/mouth/pmouth24.svg", position: { left: 76, top: 165 } },
    ],
    glasses: [
        { id: 1, itemType: "glasses", src: "/items/placeholder/empty.svg", placeholder: "/items/placeholder/glasses/empty-head.svg", position: { left: 65, top: 103 } },
        { id: 2, itemType: "glasses", src: "/items/glasses/glasses1.svg", placeholder: "/items/placeholder/glasses/pglasses1.svg", position: { left: 64, top: 103 } },
        { id: 3, itemType: "glasses", src: "/items/glasses/glasses2.svg", placeholder: "/items/placeholder/glasses/pglasses2.svg", position: { left: 63, top: 105 } },
        { id: 4, itemType: "glasses", src: "/items/glasses/glasses3.svg", placeholder: "/items/placeholder/glasses/pglasses3.svg", position: { left: 65, top: 98 } },
        { id: 5, itemType: "glasses", src: "/items/glasses/glasses4.svg", placeholder: "/items/placeholder/glasses/pglasses4.svg", position: { left: 58, top: 100 } },
        { id: 6, itemType: "glasses", src: "/items/glasses/glasses5.svg", placeholder: "/items/placeholder/glasses/pglasses5.svg", position: { left: 63, top: 103 } },
        { id: 7, itemType: "glasses", src: "/items/glasses/glasses6.svg", placeholder: "/items/placeholder/glasses/pglasses6.svg", position: { left: 62, top: 102 } },
        { id: 8, itemType: "glasses", src: "/items/glasses/glasses7.svg", placeholder: "/items/placeholder/glasses/pglasses7.svg", position: { left: 65, top: 101 } },
    ],
    outfit: [
        { id: 1, itemType: "outfit", src: "/items/outfit/foutfit1.svg", position: { left: 15, top: 190 } },
        { id: 2, itemType: "outfit", src: "/items/outfit/foutfit2.svg", position: { left: 15, top: 190 } },
        { id: 3, itemType: "outfit", src: "/items/outfit/foutfit3.svg", position: { left: 15, top: 190 } },
    ],
};