export const ITEMS_MALE = {
    head: [
        { id: 1, name: "head1", src: "/items/head1.svg" },
        { id: 2, name: "head2", src: "/items/head2.svg" },
        { id: 3, name: "head3", src: "/items/head3.svg" },
        { id: 4, name: "head4", src: "/items/head4.svg" },
        { id: 5, name: "head5", src: "/items/head5.svg" },
        { id: 6, name: "head6", src: "/items/head6.svg" },
        { id: 7, name: "head7", src: "/items/head7.svg" },
        { id: 8, name: "head8", src: "/items/head8.svg" },
        { id: 9, name: "head9", src: "/items/head9.svg" },
        { id: 10, name: "head10", src: "/items/head10.svg" },
        { id: 11, name: "head11", src: "/items/head11.svg" },
        { id: 12, name: "head12", src: "/items/head12.svg" },
        { id: 13, name: "head13", src: "/items/head13.svg" },
        { id: 14, name: "head14", src: "/items/head14.svg" },
        { id: 15, name: "head15", src: "/items/head15.svg" },
        { id: 16, name: "head16", src: "/items/head16.svg" },
        { id: 17, name: "head17", src: "/items/head17.svg" },
        { id: 18, name: "head18", src: "/items/head18.svg" },
        { id: 19, name: "head19", src: "/items/head19.svg" },
        { id: 20, name: "head20", src: "/items/head20.svg" },
        { id: 21, name: "head21", src: "/items/head21.svg" },
        { id: 22, name: "head22", src: "/items/head22.svg" },
        { id: 23, name: "head23", src: "/items/head23.svg" },
        { id: 24, name: "head24", src: "/items/head24.svg" },
        { id: 25, name: "head25", src: "/items/head25.svg" },
        { id: 26, name: "head26", src: "/items/head26.svg" },
    ],
    skin_color: [
        { id: 1, name: "skin1", src: "/items/skin1.svg" },
        { id: 2, name: "skin2", src: "/items/skin2.svg" },
        { id: 3, name: "skin3", src: "/items/skin3.svg" },
        { id: 4, name: "skin4", src: "/items/skin4.svg" },
        { id: 5, name: "skin5", src: "/items/skin5.svg" },
        { id: 6, name: "skin6", src: "/items/skin6.svg" },
        { id: 7, name: "skin7", src: "/items/skin7.svg" },
        { id: 8, name: "skin8", src: "/items/skin8.svg" },
    ],
    makeup: [
        { id: 1, name: "makeup1", src: "/items/makeup1.svg" },
        { id: 2, name: "makeup2", src: "/items/makeup2.svg" },
        { id: 3, name: "makeup3", src: "/items/makeup3.svg" },
        { id: 4, name: "makeup4", src: "/items/makeup4.svg" },
        { id: 5, name: "makeup5", src: "/items/makeup5.svg" },
    ],
    wrinkles: [
        { id: 1, name: "wrinkles1", src: "/items/wrinkles1.svg" },
        { id: 2, name: "wrinkles2", src: "/items/wrinkles2.svg" },
        { id: 3, name: "wrinkles3", src: "/items/wrinkles3.svg" },
        { id: 1, name: "wrinkles4", src: "/items/wrinkles4.svg" },
        { id: 2, name: "wrinkles5", src: "/items/wrinkles5.svg" },
        { id: 3, name: "wrinkles6", src: "/items/wrinkles6.svg" },
    ],
    hair: [
        { id: 1, name: "hair1", src: "/items/hair1.svg" },
        { id: 2, name: "hair2", src: "/items/hair2.svg" },
        { id: 3, name: "hair3", src: "/items/hair3.svg" },
        { id: 4, name: "hair4", src: "/items/hair4.svg" },
        { id: 5, name: "hair5", src: "/items/hair5.svg" },
        { id: 6, name: "hair6", src: "/items/hair6.svg" },
        { id: 7, name: "hair7", src: "/items/hair7.svg" },
        { id: 8, name: "hair8", src: "/items/hair8.svg" },
        { id: 9, name: "hair9", src: "/items/hair9.svg" },
        { id: 10, name: "hair10", src: "/items/hair10.svg" },
        { id: 11, name: "hair11", src: "/items/hair11.svg" },
        { id: 12, name: "hair12", src: "/items/hair12.svg" },
    ],
    eyes: [
        { id: 1, name: "eyes1", src: "/items/eyes1.svg" },
        { id: 2, name: "eyes2", src: "/items/eyes2.svg" },
        { id: 3, name: "eyes3", src: "/items/eyes3.svg" },
        { id: 4, name: "eyes4", src: "/items/eyes4.svg" },
        { id: 5, name: "eyes5", src: "/items/eyes5.svg" },
        { id: 6, name: "eyes6", src: "/items/eyes6.svg" },
        { id: 7, name: "eyes7", src: "/items/eyes7.svg" },
        { id: 8, name: "eyes8", src: "/items/eyes8.svg" },
        { id: 9, name: "eyes9", src: "/items/eyes9.svg" },
        { id: 10, name: "eyes10", src: "/items/eyes10.svg" },
        { id: 11, name: "eyes11", src: "/items/eyes11.svg" },
        { id: 12, name: "eyes12", src: "/items/eyes12.svg" },
        { id: 13, name: "eyes13", src: "/items/eyes13.svg" },
        { id: 14, name: "eyes14", src: "/items/eyes14.svg" },
        { id: 15, name: "eyes15", src: "/items/eyes15.svg" },
        { id: 16, name: "eyes16", src: "/items/eyes16.svg" },
        { id: 17, name: "eyes17", src: "/items/eyes17.svg" },
        { id: 18, name: "eyes18", src: "/items/eyes18.svg" },
        { id: 19, name: "eyes19", src: "/items/eyes19.svg" },
        { id: 20, name: "eyes20", src: "/items/eyes20.svg" },
        { id: 21, name: "eyes21", src: "/items/eyes21.svg" },
        { id: 22, name: "eyes22", src: "/items/eyes22.svg" },
        { id: 23, name: "eyes23", src: "/items/eyes23.svg" },
        { id: 24, name: "eyes24", src: "/items/eyes24.svg" },
        { id: 25, name: "eyes25", src: "/items/eyes25.svg" },
        { id: 26, name: "eyes26", src: "/items/eyes26.svg" },
    ],
    nose: [
        { id: 1, name: "nose1", src: "/items/nose1.svg" },
        { id: 2, name: "nose2", src: "/items/nose2.svg" },
        { id: 3, name: "nose3", src: "/items/nose3.svg" },
        { id: 4, name: "nose4", src: "/items/nose4.svg" },
        { id: 5, name: "nose5", src: "/items/nose5.svg" },
        { id: 6, name: "nose6", src: "/items/nose6.svg" },
        { id: 7, name: "nose7", src: "/items/nose7.svg" },
        { id: 8, name: "nose8", src: "/items/nose8.svg" },
        { id: 9, name: "nose9", src: "/items/nose9.svg" },
        { id: 10, name: "nose10", src: "/items/nose10.svg" },
        { id: 11, name: "nose11", src: "/items/nose11.svg" },
        { id: 12, name: "nose12", src: "/items/nose12.svg" },
        { id: 13, name: "nose13", src: "/items/nose13.svg" },
    ],
    mouth: [
        { id: 1, name: "mouth1", src: "/items/mouth1.svg" },
        { id: 2, name: "mouth2", src: "/items/mouth2.svg" },
        { id: 3, name: "mouth3", src: "/items/mouth3.svg" },
        { id: 4, name: "mouth4", src: "/items/mouth4.svg" },
        { id: 5, name: "mouth5", src: "/items/mouth5.svg" },
        { id: 6, name: "mouth6", src: "/items/mouth6.svg" },
        { id: 7, name: "mouth7", src: "/items/mouth7.svg" },
        { id: 8, name: "mouth8", src: "/items/mouth8.svg" },
        { id: 9, name: "mouth9", src: "/items/mouth9.svg" },
        { id: 10, name: "mouth10", src: "/items/mouth10.svg" },
        { id: 11, name: "mouth11", src: "/items/mouth11.svg" },
        { id: 12, name: "mouth12", src: "/items/mouth12.svg" },
        { id: 13, name: "mouth13", src: "/items/mouth13.svg" },
        { id: 14, name: "mouth14", src: "/items/mouth14.svg" },
        { id: 15, name: "mouth15", src: "/items/mouth15.svg" },
        { id: 16, name: "mouth16", src: "/items/mouth16.svg" },
        { id: 17, name: "mouth17", src: "/items/mouth17.svg" },
        { id: 18, name: "mouth18", src: "/items/mouth18.svg" },
        { id: 19, name: "mouth19", src: "/items/mouth19.svg" },
        { id: 20, name: "mouth20", src: "/items/mouth20.svg" },
        { id: 21, name: "mouth21", src: "/items/mouth21.svg" },
        { id: 22, name: "mouth22", src: "/items/mouth22.svg" },
        { id: 23, name: "mouth23", src: "/items/mouth23.svg" },
        { id: 24, name: "mouth24", src: "/items/mouth24.svg" },
        { id: 25, name: "mouth25", src: "/items/mouth25.svg" },
        { id: 26, name: "mouth26", src: "/items/mouth26.svg" },
        { id: 27, name: "mouth27", src: "/items/mouth27.svg" },
    ],
    eyebrows: [
        { id: 1, name: "eyebrows1", src: "/items/eyebrows1.svg" },
        { id: 2, name: "eyebrows2", src: "/items/eyebrows2.svg" },
        { id: 3, name: "eyebrows3", src: "/items/eyebrows3.svg" },
        { id: 4, name: "eyebrows4", src: "/items/eyebrows4.svg" },
        { id: 5, name: "eyebrows5", src: "/items/eyebrows5.svg" },
        { id: 6, name: "eyebrows6", src: "/items/eyebrows6.svg" },
        { id: 7, name: "eyebrows7", src: "/items/eyebrows7.svg" },
        { id: 8, name: "eyebrows8", src: "/items/eyebrows8.svg" },
        { id: 9, name: "eyebrows9", src: "/items/eyebrows9.svg" },
    ],
    beard: [
        { id: 1, name: "beard1", src: "/items/beard1.svg" },
        { id: 2, name: "beard2", src: "/items/beard2.svg" },
        { id: 3, name: "beard3", src: "/items/beard3.svg" },
        { id: 4, name: "beard4", src: "/items/beard4.svg" },
    ],
    glasses: [
        { id: 1, name: "glasses1", src: "/items/glasses1.svg" },
        { id: 2, name: "glasses2", src: "/items/glasses2.svg" },
        { id: 3, name: "glasses3", src: "/items/glasses3.svg" },
        { id: 4, name: "glasses4", src: "/items/glasses4.svg" },
        { id: 5, name: "glasses5", src: "/items/glasses5.svg" },
        { id: 6, name: "glasses6", src: "/items/glasses6.svg" },
        { id: 7, name: "glasses7", src: "/items/glasses7.svg" },
        { id: 8, name: "glasses8", src: "/items/glasses8.svg" },
        { id: 9, name: "glasses9", src: "/items/glasses9.svg" },
    ],
    outfit: [
        { id: 1, name: "outfit1", src: "/items/outfit1.svg" },
        { id: 2, name: "outfit2", src: "/items/outfit2.svg" },
        { id: 3, name: "outfit3", src: "/items/outfit3.svg" },
    ],
};

export const ITEMS_FEMALE = {
    head: [
        { id: 1, name: "head1", src: "/items/head1.svg" },
        { id: 2, name: "head2", src: "/items/head2.svg" },
        { id: 3, name: "head3", src: "/items/head3.svg" },
        { id: 4, name: "head4", src: "/items/head4.svg" },
        { id: 5, name: "head5", src: "/items/head5.svg" },
        { id: 6, name: "head6", src: "/items/head6.svg" },
        { id: 7, name: "head7", src: "/items/head7.svg" },
        { id: 8, name: "head8", src: "/items/head8.svg" },
        { id: 9, name: "head9", src: "/items/head9.svg" },
        { id: 10, name: "head10", src: "/items/head10.svg" },
        { id: 11, name: "head11", src: "/items/head11.svg" },
        { id: 12, name: "head12", src: "/items/head12.svg" },
        { id: 13, name: "head13", src: "/items/head13.svg" },
        { id: 14, name: "head14", src: "/items/head14.svg" },
        { id: 15, name: "head15", src: "/items/head15.svg" },
        { id: 16, name: "head16", src: "/items/head16.svg" },
        { id: 17, name: "head17", src: "/items/head17.svg" },
        { id: 18, name: "head18", src: "/items/head18.svg" },
        { id: 19, name: "head19", src: "/items/head19.svg" },
        { id: 20, name: "head20", src: "/items/head20.svg" },
        { id: 21, name: "head21", src: "/items/head21.svg" },
        { id: 22, name: "head22", src: "/items/head22.svg" },
        { id: 23, name: "head23", src: "/items/head23.svg" },
        { id: 24, name: "head24", src: "/items/head24.svg" },
        { id: 25, name: "head25", src: "/items/head25.svg" },
        { id: 26, name: "head26", src: "/items/head26.svg" },
    ],
    skin: [
        { id: 1, name: "skin1", src: "/items/skin1.svg" },
        { id: 2, name: "skin2", src: "/items/skin2.svg" },
        { id: 3, name: "skin3", src: "/items/skin3.svg" },
        { id: 4, name: "skin4", src: "/items/skin4.svg" },
        { id: 5, name: "skin5", src: "/items/skin5.svg" },
        { id: 6, name: "skin6", src: "/items/skin6.svg" },
        { id: 7, name: "skin7", src: "/items/skin7.svg" },
        { id: 8, name: "skin8", src: "/items/skin8.svg" },
    ],
    makeup: [
        { id: 1, name: "makeup1", src: "/items/makeup1.svg" },
        { id: 2, name: "makeup2", src: "/items/makeup2.svg" },
        { id: 3, name: "makeup3", src: "/items/makeup3.svg" },
        { id: 4, name: "makeup4", src: "/items/makeup4.svg" },
        { id: 5, name: "makeup5", src: "/items/makeup5.svg" },
    ],
    wrinkles: [
        { id: 1, name: "wrinkles1", src: "/items/wrinkles1.svg" },
        { id: 2, name: "wrinkles2", src: "/items/wrinkles2.svg" },
        { id: 3, name: "wrinkles3", src: "/items/wrinkles3.svg" },
        { id: 1, name: "wrinkles4", src: "/items/wrinkles4.svg" },
        { id: 2, name: "wrinkles5", src: "/items/wrinkles5.svg" },
        { id: 3, name: "wrinkles6", src: "/items/wrinkles6.svg" },
    ],
    hair: [
        { id: 1, name: "hair1", src: "/items/hair1.svg" },
        { id: 2, name: "hair2", src: "/items/hair2.svg" },
        { id: 3, name: "hair3", src: "/items/hair3.svg" },
        { id: 4, name: "hair4", src: "/items/hair4.svg" },
        { id: 5, name: "hair5", src: "/items/hair5.svg" },
        { id: 6, name: "hair6", src: "/items/hair6.svg" },
        { id: 7, name: "hair7", src: "/items/hair7.svg" },
        { id: 8, name: "hair8", src: "/items/hair8.svg" },
        { id: 9, name: "hair9", src: "/items/hair9.svg" },
        { id: 10, name: "hair10", src: "/items/hair10.svg" },
        { id: 11, name: "hair11", src: "/items/hair11.svg" },
        { id: 12, name: "hair12", src: "/items/hair12.svg" },
        { id: 13, name: "hair13", src: "/items/hair13.svg" },
        { id: 14, name: "hair14", src: "/items/hair14.svg" },
        { id: 15, name: "hair15", src: "/items/hair15.svg" },
        { id: 16, name: "hair16", src: "/items/hair16.svg" },
        { id: 17, name: "hair17", src: "/items/hair17.svg" },
        { id: 18, name: "hair18", src: "/items/hair18.svg" },
        { id: 19, name: "hair19", src: "/items/hair19.svg" },
        { id: 20, name: "hair20", src: "/items/hair20.svg" },
        { id: 21, name: "hair21", src: "/items/hair21.svg" },
        { id: 22, name: "hair22", src: "/items/hair22.svg" },
        { id: 23, name: "hair23", src: "/items/hair23.svg" },
        { id: 24, name: "hair24", src: "/items/hair24.svg" },
    ],
    eyes: [
        { id: 1, name: "eyes1", src: "/items/eyes1.svg" },
        { id: 2, name: "eyes2", src: "/items/eyes2.svg" },
        { id: 3, name: "eyes3", src: "/items/eyes3.svg" },
        { id: 4, name: "eyes4", src: "/items/eyes4.svg" },
        { id: 5, name: "eyes5", src: "/items/eyes5.svg" },
        { id: 6, name: "eyes6", src: "/items/eyes6.svg" },
        { id: 7, name: "eyes7", src: "/items/eyes7.svg" },
        { id: 8, name: "eyes8", src: "/items/eyes8.svg" },
        { id: 9, name: "eyes9", src: "/items/eyes9.svg" },
        { id: 10, name: "eyes10", src: "/items/eyes10.svg" },
        { id: 11, name: "eyes11", src: "/items/eyes11.svg" },
        { id: 12, name: "eyes12", src: "/items/eyes12.svg" },
        { id: 13, name: "eyes13", src: "/items/eyes13.svg" },
        { id: 14, name: "eyes14", src: "/items/eyes14.svg" },
        { id: 15, name: "eyes15", src: "/items/eyes15.svg" },
        { id: 16, name: "eyes16", src: "/items/eyes16.svg" },
        { id: 17, name: "eyes17", src: "/items/eyes17.svg" },
        { id: 18, name: "eyes18", src: "/items/eyes18.svg" },
        { id: 19, name: "eyes19", src: "/items/eyes19.svg" },
        { id: 20, name: "eyes20", src: "/items/eyes20.svg" },
        { id: 21, name: "eyes21", src: "/items/eyes21.svg" },
        { id: 22, name: "eyes22", src: "/items/eyes22.svg" },
        { id: 23, name: "eyes23", src: "/items/eyes23.svg" },
        { id: 24, name: "eyes24", src: "/items/eyes24.svg" },
        { id: 25, name: "eyes25", src: "/items/eyes25.svg" },
        { id: 26, name: "eyes26", src: "/items/eyes26.svg" },
    ],
    nose: [
        { id: 1, name: "nose1", src: "/items/nose1.svg" },
        { id: 2, name: "nose2", src: "/items/nose2.svg" },
        { id: 3, name: "nose3", src: "/items/nose3.svg" },
        { id: 4, name: "nose4", src: "/items/nose4.svg" },
        { id: 5, name: "nose5", src: "/items/nose5.svg" },
        { id: 6, name: "nose6", src: "/items/nose6.svg" },
        { id: 7, name: "nose7", src: "/items/nose7.svg" },
        { id: 8, name: "nose8", src: "/items/nose8.svg" },
        { id: 9, name: "nose9", src: "/items/nose9.svg" },
        { id: 10, name: "nose10", src: "/items/nose10.svg" },
        { id: 11, name: "nose11", src: "/items/nose11.svg" },
        { id: 12, name: "nose12", src: "/items/nose12.svg" },
        { id: 13, name: "nose13", src: "/items/nose13.svg" },
    ],
    mouth: [
        { id: 1, name: "mouth1", src: "/items/mouth1.svg" },
        { id: 2, name: "mouth2", src: "/items/mouth2.svg" },
        { id: 3, name: "mouth3", src: "/items/mouth3.svg" },
        { id: 4, name: "mouth4", src: "/items/mouth4.svg" },
        { id: 5, name: "mouth5", src: "/items/mouth5.svg" },
        { id: 6, name: "mouth6", src: "/items/mouth6.svg" },
        { id: 7, name: "mouth7", src: "/items/mouth7.svg" },
        { id: 8, name: "mouth8", src: "/items/mouth8.svg" },
        { id: 9, name: "mouth9", src: "/items/mouth9.svg" },
        { id: 10, name: "mouth10", src: "/items/mouth10.svg" },
        { id: 11, name: "mouth11", src: "/items/mouth11.svg" },
        { id: 12, name: "mouth12", src: "/items/mouth12.svg" },
        { id: 13, name: "mouth13", src: "/items/mouth13.svg" },
        { id: 14, name: "mouth14", src: "/items/mouth14.svg" },
        { id: 15, name: "mouth15", src: "/items/mouth15.svg" },
        { id: 16, name: "mouth16", src: "/items/mouth16.svg" },
        { id: 17, name: "mouth17", src: "/items/mouth17.svg" },
        { id: 18, name: "mouth18", src: "/items/mouth18.svg" },
        { id: 19, name: "mouth19", src: "/items/mouth19.svg" },
        { id: 20, name: "mouth20", src: "/items/mouth20.svg" },
        { id: 21, name: "mouth21", src: "/items/mouth21.svg" },
        { id: 22, name: "mouth22", src: "/items/mouth22.svg" },
        { id: 23, name: "mouth23", src: "/items/mouth23.svg" },
        { id: 24, name: "mouth24", src: "/items/mouth24.svg" },
        { id: 25, name: "mouth25", src: "/items/mouth25.svg" },
        { id: 26, name: "mouth26", src: "/items/mouth26.svg" },
        { id: 27, name: "mouth27", src: "/items/mouth27.svg" },
    ],
    eyebrows: [
        { id: 1, name: "eyebrows1", src: "/items/eyebrows1.svg" },
        { id: 2, name: "eyebrows2", src: "/items/eyebrows2.svg" },
        { id: 3, name: "eyebrows3", src: "/items/eyebrows3.svg" },
        { id: 4, name: "eyebrows4", src: "/items/eyebrows4.svg" },
        { id: 5, name: "eyebrows5", src: "/items/eyebrows5.svg" },
        { id: 6, name: "eyebrows6", src: "/items/eyebrows6.svg" },
        { id: 7, name: "eyebrows7", src: "/items/eyebrows7.svg" },
        { id: 8, name: "eyebrows8", src: "/items/eyebrows8.svg" },
        { id: 9, name: "eyebrows9", src: "/items/eyebrows9.svg" },
    ],
    mustache: [
        { id: 1, name: "mustache1", src: "/items/mustache1.svg" },
        { id: 2, name: "mustache2", src: "/items/mustache2.svg" },
        { id: 3, name: "mustache3", src: "/items/mustache3.svg" },
        { id: 4, name: "mustache4", src: "/items/mustache4.svg" },
    ],
    glasses: [
        { id: 1, name: "glasses1", src: "/items/glasses1.svg" },
        { id: 2, name: "glasses2", src: "/items/glasses2.svg" },
        { id: 3, name: "glasses3", src: "/items/glasses3.svg" },
        { id: 4, name: "glasses4", src: "/items/glasses4.svg" },
        { id: 5, name: "glasses5", src: "/items/glasses5.svg" },
        { id: 6, name: "glasses6", src: "/items/glasses6.svg" },
        { id: 7, name: "glasses7", src: "/items/glasses7.svg" },
        { id: 8, name: "glasses8", src: "/items/glasses8.svg" },
        { id: 9, name: "glasses9", src: "/items/glasses9.svg" },
    ],
    body: [
        { id: 1, name: "body1", src: "/items/body1.svg" },
        { id: 2, name: "body2", src: "/items/body2.svg" },
        { id: 3, name: "body3", src: "/items/body3.svg" },
    ],
};